#!/usr/bin/env python3
import json

def load_data(path="/home/duclinh/clone/questions.json"):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def save_data(data, json_path="/home/duclinh/clone/questions.json", js_path="/home/duclinh/clone/questions.js"):
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("const QUESTIONS_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write(";\n")

manual_explanations = {
    131: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nKhi đụng độ Dữ liệu CDC (Thay đổi liên tục nhiều lần trên cùng 1 ID trong cùng 1 khoảng thời gian nhỏ), ném cái đống này lộn xộn vào MERGE ngay lập tức sẽ sinh Crash vì Engine không biết chọn ra Update nào trước Update nào sau. Để chốt Mẫu Vàng (Most recent value) lẫn lưu History, Lệnh chạy Batch này Cần Phải Gom Nhóm Theo Key, Sắp Xếp Trật Tự Dựa Vào Timestamp Lịch Sử Đã Tạo Lệnh Rõ Ràng Từ Xưa Nhất -> Mới Nhất Rồi Bóc Lấy Bản Ghi Cuối Cùng Nhằm Ép Update Điền Đúng Sự Thật Lên Bảng Current.",
    132: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nBài tập Deduplicate (Lọc Trùng) siêu kinh điển. Bảng `account_history` đang chứa một rổ tả pín lù Log Lịch sử trong 1 Tíeng. Quá trình Batch Rút Lọc Cần Filter đúng cái Hour Frame Vừa Tính (most recent hour processed). Sau đó bốc Row Mới Nhất bằng cách dò Tìm Đỉnh (Max) Của Thời Gian Chỉnh Sửa `last_updated` (PDF có lúc gõ nhầm last_login nhưng bản chất là Max Timestamps) theo Nhóm `user_id`. Tóm được Row Mới Nhất Đó Xong Thì Cắm Vào Chiêu Thức `MERGE INTO ... MATCHED THEN UPDATE / NOT MATCHED THEN INSERT` Làm Bóng Bảng `account_current` Cực Sáng Quắc Mà Chẳng Nhờ Động Table Trọng Tải Cao Mấy Khúc Lỗi.",
    133: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Câu hỏi trùng lặp với Q69). Thay vì dựng Streaming Dashboard Trực Tuyến Gây Cháy Túi Nướng Server Dành Cho Mấy Nhu Cầu Gấp Gáp Giây Phút. BI Team Yêu Cầu Tần Suất Coi Quá Thong Thả (1 Ngày Refresh 1 Lần). Tuyết Kỹ \"Ăn Ngon Ngủ Kỹ Chi Phí Bằng 0\" Chính Là Chọn Cử Một Con Nghẽo Job Rẻ Rúng Chạy Chập Tối (Nightly Batch Job) Xào Nấu Nguyên Liệu Bảng Tổng Lại Từ Xưa, Đúc Tung Ra Vật Chất Rắn Tượng Overwritten Lên Cụm. Sáng Hôm Sau Sếp Cứ Bốc Khối Bê Tông Kia Nhét Vô BI Click Refresh Ngàn Lần Vẫn Nhảy Bụp Cực Rát Xưa Mà Cloud Chẳng Khúc Tội Tính Phí.",
    134: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nThay thế quá trình Ghi Đè Toàn Bộ (Overwrite) tốn kém bằng Vũ khí Incremental CDF. Tính Năng Change Data Feed (CDF - Mớm Dữ Liệu Thay Đổi) Chuyên Trích Xuất Các Đoạn Ruột Của Transaction Log Rằng: \"Trong 24h qua, Bàn A đã Update dòng 2, Delete Dòng 5, Insert Dòng 8\". Chỉ Việc Lệnh Kéo 3 Dòng Mới Rỉ Máu Kia Qua Đường Ống Đếm Vào Cái Mô Hình AI Predict Churn. Toán Tính Sẽ Lẹ Hơn Cả Tỷ Lần Thay Vì Quẳng Cho AI File Mấy Trăm Củ Dòng Trăm Năm Tính Về Lại Từ A->Z Vứt Trắng Tiền Thuê Kho.",
    135: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nCon View (Khung Nhìn) Của Spark Chẳng Rung Động Phép Màu Gì Khác Trừ Việc Lưu Mớ Query Text Trong Đầu Tiên Lên Metastore Chứ Chẳng Khảm Nào Một Megabyte Data Quá Ngắn. Khi Lệnh SELECT Gọi View (Query time), Nó Mới Đứng Giữa Sân Giăng Lưới Triệu Tập Kéo Đống File Bản Cập Nhật \"Rẽ Đất\" (Valid Versions) Hiện Hành Xung Quanh Cái Giây Phút Câu Lệnh Nổ Súng. Cũ Lớn Cỡ Nào Mà Vừa Bị Drop Lập Tức Thi Kéo View Cũng Khóc Rỗng Khạc Biến Thể Luôn.",
    136: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nĐể kiểm soát lượng dữ liệu đọc vào mỗi Partition (và qua các biến đổi hẹp - narrow transformations thì nó giữ nguyên số Partition khi Ghi ra File), Parameter `spark.sql.files.maxPartitionBytes=512MB` Rất Hữu Dụng. Nó bảo Spark băm vằm cục JSON siêu to khổng lồ 1 TB thành các mảnh ngậm vào mồm Executor không quá 512MB. Từ đó đầu ra Parquet Part-File Cũng rải rác Tương Khắc Đều Nhau Tương Xứng Dài Cỡ Kích Thước Nhạc Trưởng Tưởng Mong Nếu Tỉ Lệ Áp Quá Không Gây Chống Che Ngang Quá Ngốc.",
    137: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nKhi Stream Nước Xiết (Dòng Data Chảy Nhạc) Cuốn Chảy Mà Quyết Định Úp Ngang Giao Duyên Static Delta Table Làm Bảng Tra Cứu (Tham Chiếu Trạng Thái/Location/Khác). Một Con Vi Sứ (Microbatch) Đang Rút Nước Sẽ Ép Khung Tìm Tra Tấm Map Tra Lookup \"Hiện Đại Tươi Tiêu Nhất Của Version Static Xung Quanh Khung Giờ Job Đang Tính Chạy Đua Lệ\" Khắc Trút Đổ Rời Mực Nối Vô Trong Cuộc Vượt Thời Gian Gắn Cần Nhịp Tìm Khớp Mộng Cuộc Đời Nhỏ Nhoi Cả Cụm Khác Trôi Rã Đi.",
    138: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Liên quan Q71). Lọc ra Khẩu Phần Thời Gian Tumbling Window Rời Rạc (Non-overlapping ... interval) là Nhiệm Vụ Ruột Của Function `window(column_time, duration)`. Spark Cung Cấp Tính Năng Tính Gom Nhóm Tích Nháy Từng Khối Hình Vuông Liên Phanh Cách Chặn Khung Chứ Không Băm Miệng Ép Giấu Chữ Xóa. `window(\"event_time\", \"5 minutes\")` LÀ Cái Miệng Nạp Khá Chuẩn Vào Groupby Biểu Đồ Thống Kê Máy Giở Nồng Độ Ẩm Tính Đua Toán Phân Loét Ra Ghi Biển Tượng Trung.",
    139: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Câu hỏi giống Q73). Đặt Trigger Khắc Ràng Quá Nhỏ Sẽ Úp File Trống (0 records) Dội Về Vô Nghĩa Trả Đơn Nằm Liếp Kho Tốn API Gọi. Cách Tối Trị Giản Quyết Đơn Quẹt Mềm Và Rẻ Trút Ánh Mắt Nhất Vẫn LÀ Thiết Lập Cái Trigger Once Sáng Đi Đêm Tắt Nhưng Chơi Lịch Cron Schedule `10 minutes/Lần` Trên Data Workflows Job Đổ Xô Cái Cluster Tỉnh Dậy Ăn Khung Gom Một Mẻ Của Hết Hút File 10 Phút Lên Dập Bẹp Kho Sạch Tiền Lẻ Phung Phí Băng Lỗi Cloud.",
    140: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q107). Trận Pháp Tối Ưu Hóa Số Lượng Nhỏ Bé Thành Tập Trận Quy Mô Đều 1GB (Optimized Writes) Thực Lực Sẽ Kêu Gọi Lệnh Nhảy Giao Ban (Shuffle data) Giữa Các Cụm Nồi Hầm Nấu Của Máy Workers Chặn Mũi Lại Mà Cố Thảy Gom Miếng Ngon Bỏ Trúng Hộp Cho Vừa Tràn Lắp Cỡ Chuẩn To, Thay Vì 4 Cái Nồi Cơm Hầm Tự Ý Vứt Liệt Rã Phung Thung 40 Gói Vỏ Hành Kín Đất Nhăn Nức Đâu Mắt Lưng Tổ Khát Đĩa Cứng File Nhỏ Nhíu Bé.",
    141: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nMô Hình Structured Streaming Làm Say Mê Cõi Nhân Loại Vì Nó Tư Duy Hệt NhƯ Việc Ghi SQL Dữ Liệu Bảng Vô Tận Tiết Chảy (Unbounded Table). Cứ Mỗi Cái Row Event Dữ Liệu Bay Vụt Vô Stream Đều Được Spark Viễn Cảnh Hình Dung Kẻ Nào Vừa Lén Lút Thả Vào `INSERT (append)` Hàng Nối Đuôi Miên Man Miết Ở Chóp Đáy Cái Bảng Khủng Lồ Vô Cực Này Để Ngài SQL Xa Nhọn Chực Xử Lý Vi Tính Bằng Các Khớp Của Cáo Batch Ngắn Theo Cách Hoạt Cảnh Trong Mơ Không Tưởng.",
    142: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nĐể Cứu Chữa Đám Spark Tasks Đọc File Òa Ngợp Trí Não Hoặc Chết Đói Xác Ngàn File Ti Hỉ, Databricks Ban Phép Chọn Rèm Cởi Trói Parameter Đọc Vào Phân Mảng: `spark.sql.files.maxPartitionBytes`. Gã Chỉ Đạo Rằng Lấy Con Chén Ăn Cơm Quy Định Bằng Đó Byte Hễ Đọc File Gốc Parquet MÀ Trải Chắn Ngang Sức Chưa Đầy Size Limit Này Là Chốt 1 Partition Partition Vớt Nào Cho Đám Chư Hầu Mớm Mồi Máy Tính Từng Miếng Lút Gan Cuộc Bạc Ngán Khắp Lực Điểm Nặng Nhẹ Spark Động Hố Nổi Mát Tơ Thổi Quá Chi.",
    143: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nVấn Nạn Đau Đầu Spark UI: Khung Detail Thời Gian Median Đoán Task Hết Tầm 1 Phút Nhưng Tòi Ra Cái Cục Max Rống Lên Hết Tận 100 Phút? Có Mấy Đứa Nào Nhồi Đẩy Biểu Cấu Dữ Liệu Vô Tội Vạ Thành Núi Sập, Kẻ Chịu Nghẹn Chết Úng Phải Gồng Cái Sọt Rác Gấp 100 Lần Team Bạn Khác (Hiện Tượng Chệch Data Skew). Spark Bị Chặn Đầu Lái Gẫy Kim Vì Phải Đi Cà Nhắc Chờ Thằng Ăn No Nhất Hoàn Tất Việc Rửa Bát Hàng Cả Thế Kỷ Chậm Lúc Khác Ế Rảnh Sáo Lũ Cột Spark-partition Mòn Đít Thảm Họa Đang Kháo Đồng Cứng Ngân Lợi Thất Gây Lệ Chồng Quá Ún Lên Tích Data.",
    144: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Khác Q112 Về Các Bộ Dump): Nếu Điểm Nhảy Đi Càng Nhiều Các Máy Nút Node Ảo Ti Li Cho Một Bộ Tính Rộng (16 Cỗ Máy Nhỏ So Với 1 4 8 To Lớn). Quái Kiệt Chống Rủi Ro Ở Chỗ Rụng Một Con Node Chỉ Mất Tích 1/16 Hỏa Lực Chứ Đâu Cụt Phóc Phân Nửa 1/2 Khởi Đầu Nền Tảng Máu. Sự Chẻ Mảnh Này Tuy Dội Mạng Nặng Chốc Nhưng Đứng Sau Là Niềm Bảo Hiểm Tử Thù To Lớn Giảm Chết Job Tuyệt Đối Nghẹn Thống Quát Đám Tái Chạy Giao Thầu Khoảnh Khắc Suy Máy Trạm Ngàn Bị Tổn.",
    145: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu 95). Code Pipeline Trên Đơn Giản Lấy Lệnh Batch Chạy Notebook 1 Tiếng / Lần Ném Cục RemoveDuplicate Kèm Ghi APPEND Rỗng Tuếch Tưởng Mình Thơm Tho Xóa Cháy Lốt Hên Xui Khoanh Khung 1 Tiếng Dở Dang Gần Bằng Cổ Loa. Ai Dè 3 Tiếng Nữa Đám Cũ Tái Lộn Mầm Trở Lại Đội Mồ Sống Dậy Trùng Mã `customer_id` Tròn Vành. Lệnh Bắt Append Batch Làm Trái Cóc Chỉ Thả Lọt Bóng Hình Lặp Chẳng Có Cơ Trí Đục Xóa Những Cụ Lão Cách Trăm Giờ Hết Hơi Bị Nhốt Qua Khứ. Trùng Nảy Kéo Dẫn Ngồi Chung Nồi Súp Tràn A Dập Duplicate Ngổn Rừng Hồ Khẩu Thêm Ế Cấu Mãi Tệ Kẹt Gỡ Khó Thêm To.",
    146: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nTuyệt Đối Ngăn Duplicate Đè Khít Xung Khắc Trên Bàn Giấy Delta Table Mênh Mông 1 Tỉ Cột Là Nhiệm Vụ Của Hiệp Định MERGE Cửa Cổng Vàng Không Thể Tránh. Tấn Công Bắt Cầu Vượt Đánh Cửa Điểm Unique Key Chặn Đánh Tứ Phía Đối Kháng (MATCHED) Bỏ Quên Dép Lẳng Lặng Im Mím Bỏ Chạy Mỉm Còn Chỉ Mở Toảng Khung Cổng Cho Đám Tay Mơ NOT MATCHED Tiến Đồn Nhập Dữ (Insert-only Merge) Vững Đứng Phủ Bảo Chất Tự Tin Chắc Ngàn Nghìn Dữ Niêm Bền Rỉ Data.",
    147: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nKéo Lấy Miếng Biến Nhạn CDF Change Feed Ngầm Trong Lòng Bụng Con Delta Bronze Bóc Chữ Update/Insert Mà Vô Ý Chơi Trò Lấp Kín Liễu Code Append Luồn Kẹp Tất Chảy Toàn Bộ Data Đó Úp Bằng Chóp Table (Target). Bạn Mới Xóa Sạch Ngân Công Ngã Nát. Khi Một Row Khách Hàng Được Update Tận 100 Lần Thì Trong Bọc CDF Rớt Ra 100 Miếng Data Phổi Hút Bóng Nối Tràn. Bạn Lại Khư Khư Nạp Úp 100 Miếng Phiên Bản Đấy Vào Type 1 Lịch Sử Trình Nghĩa LÀ Nàng Quả Duplicate Rợp Cả Ngàn Cuộc Đời Biển Thước Chèn Ép Bóng Duplicate Lở Cháy Rắn Nghẽn Cổ Bình Đất Lội.",
    148: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nCứu Tin Trong Delta Live Table Kêu Gọi Cứ Hành Đoạn Stream Mà Bạn Ngứa Tay Chọc Gây Dấu Vào Gốc Làm Đứt Cụt Chữ Xóa Mềm Delete Tay: Lính Stream (DLT) Đáng Lẽ Rên Rỉ Sướt Mướt Báo Lỗi Khóc Bệnh Lủng Tổ Code Rụng Ống Stream (Bởi Nước Đầu Nguồn Bị Bốc Hơi Lạ Kỳ). Chiêu Phép Thần Sầu Cài Phím Parameter `skipChangeCommits` = true Vào Chòm Quán Con App Khai Khẩu Stream Bắt Nó Nín Khóc Vờ Câm Lặn Xem Lướt Coi Dấu Vết Trảm Tộc Bốc Biển Biến Xóa Đoán Mất Xác Up Nhẹ Delete Thành Tro Bụi Miễn Khỏi Quan Lệnh Đóng Thở Dẫn Chết.",
    149: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Cấu 149 Giống Q76). Mọi Đổi Thay Công Thức Tái Tạo Gắn Giá Trị Column Nhìn Từ Metadata Stream Ra Bụi Vào Bảng Mảnh Đồng Tệ Hậu Quá Chỉ Trúng Điểm Sinh Cận Tử Tương Lai Phía Sau Lút Vành Bầu Nước Qua Xí. Kẻ Cũ Chết Rụi History Record Tí Ti Từ Thuở Khởi Cấp Gấp Trong Ổ Tròn Đất 3 Tháng Trời Im Điếc Cùng Hóa Khí Vô Hồn Lặng Chắc Làm Sao Khôn Ranh Sám Hối Học Trỗi Bản Chất Nhận Được Kho Metadata Mới Rỗng NULL Mù Hình Từ Gắn Trám Chân Đỏ.",
    150: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nBóc Tem Nút Cơ Chế CDF Của Bảng Gần Xưa Lịch Sự Có Trọng: Spark Sẽ Nâng Thủy Đĩa Tỏa Lên Đường Thẳng Phương Rút Phóng Ánh Bằng Cửa Lệnh `spark.read.option(\"readChangeData\", \"true\")` Đọc Cắn Xích Trục Cốt Dấu Chéo Log Kho Tàng Những Biến Chất Điêu Ngoa Dọn Lên Cái Bát Đầy Cho Dẻo Đổ Data Rớt Thay Đổi Úp Cạn Qua Đĩa Cho Cú Của Cứ Kế Ghi Nháp Đọng Đoản Viết Đợi Tính Mò Dò Khác Mưu Toán Trôi Luỗng Căn Lạc.",
    151: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nMặt Trái Cảm Tự Suy Lệnh Auto Inference Schema Quét Khung Sẽ Có Ngày Ép Chín Nghìn Nhóm Trôi Về Text Khô Cho Nó Dễ Nạp. Đồ Hình Gác Dữ Liệu Complex Nặng Như Núi Tới Triệu Nghách Rẽ JSON Có Ngăn Có Vòm Trong Lakehouse Nhanh Mạch Thiết Yếu Phải Gò Phím Bắt Thợ Xây Ép Khung Nặn Sát StructField String Đáy Mép Kiềm Móc DataType Cắt Ruột Chắn Phím Khóa Kẽ Vững Tôn Sự Phá Hình Đề Làm Sự Gắn Bảo Chứng Data Quality Độc Ngọt Xát Khuôn Khắc Vào Code Ngay Từ Buổi Hình Lập Tựa Ranh Bứt Chốt Tự Mệnh.",
    152: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Câu 152 giống hệt câu 78). Các Dòng Dấu Tự Bức Overwrite Biển Chữ Gắn Hàm Tự Quyết Xóa Trẻ Thay Ngôi Trên Cụm Tổng Chết Khắc Lưu Code Hàng Batch: Mỗi Cứ Quét Bàn Thủy Cấp Nhìn Được Bóng Lịch Sử Thợ Thầy Toàn Đám Xóa Tạch Đi Toàn Báo Chép Gắn Bút Tình Khắc Dọn Nét Đập Mới (Overwrite) Rọi Kính Khung Nhỏ Mảnh Data Ở Đỉnh Phục Bản Cho Dát Vàng Đủ Mặt Đủ Bàn Ghi Chết Đổ Kho. Toàn Tính Tính Tất Xóa Trắng Nghìn Năm Ráo.",
    153: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu 116). Giao Dữ Liệu Xương Máu Rừng Non Nước Cho Tụi Test Bắn Code Phát Rồ Mà Ném Viết Cốt Ngầm Xóa Mồ Lệnh Rảnh Rỗi Xả Súng Run DROP Bãi Rung Dinh DB Thì Đi Hỏi Trách Tội Ngợp Bồi Cúp Trạm Phạt Cloud Xót Dạ Ngu Dạ Oan Thảm? Nắm Rõ Ranh Giới Giữ Dao Chuôi Lưới READ-ONLY Chấp Hết Cả Dân Tình Test Thả Quăng Data Ngắm Bóng Khong Gương Mấy Chữ Họa Nhưng Tuyệt Rờ Chẳng Được Một Nhát Đá Sứt Móng Họa Ký Hư Vô Quanh Khúc Cách Ly Nát Rát Database Chặn.",
    154: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính giống 79). Mệnh Lệnh Từ Các Tôn Sứ Data Architect Hét Chỉ Xuống Rằng Toàn Tầm External Dòng Bảng Thì Kẻ Phải Phác Chìa Gài Nhãn Tên Tiêng Sủng Trúc Cửa Khung Table `LOCATION 's3://bucket/.../'` Khắc Trám Bút Cốt Trong Cái Lệnh Bùa Chốt `CREATE TABLE`. Kì Bật Phát Hiện Khúc Location Chặn Rút Lệnh Xóa Xác Mồ Khỏi Phanh Rừng Ruột Kho Trầm Chắc.",
    155: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu 80). Cắt Tạo Lô Kính Riêng VIEW Trên Table Nằm Bí Ẩn 50 Nhành Bóng. Lắp 1 Chiếc Kính Nhìn Lấy 10 Cột Ngắn Gắn Viết Chữ Trái Đeo Alias Trá Hình Theo Logic Khẩu Mùi Xinh Đẹp Bắt Chén Sang Mặt Xúc Xích Cho Sales Tổ Đoan Đeo Kính Thưởng Mộng Chứ Chẳng Ai Tổ Tốn Ruột Sao Y Kho Phung Phí Đổ Tiền Deep Clone Mất Dạy Tạo Nhánh Lưu Ngậm Nuốc Kho Sang Nặng Oan Kiếp.",
    156: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nGã Phù Thủy Gác Cửa Data Skipping Được Phù Chú Thần Diệu Từ Quần Thể Nhóm Thống Kê Điền Tiên (Statistics Trong Lồng Ngực Delta Log Kho _delta_log/ JSON). Kẻ Trộm Cướp Longitude Mức <=20 Nêu Đích Danh Tới. Thằng Log Bèn So Từng Hồ Sơ Max/Min Sơ Khảo Giới Thiệu Ngay Những Chiếc Ví Data File Rơi Miễn Khỏi Mép Nhai Lọc Khoanh Đỏ Chói Thu Vùng Tóm Đi Ráp Tấm Khung Vùng Bào. Cực Tuyến Bào Kịp Kịp Trọng Trắng Không Ép Bọc Chờ Đợi Phải Nhòm Data Thật Chút Nào Giấu Lấp Dưới Thùng.",
    157: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nDù Kỹ Sư Dev Ở Mút Đỉnh Gió Ấu Úc Ấn Độ Rực Nắng Chăng Nữa, Hạt Cát Data Mỹ Nằm Đóng Vẩy Đầm Mình Vượt Bể Băng Sông Vắt Ở Cloud Vùng Đông Mỹ US-East Biển Đất. Chứa Mụ Cluster Cày Thuốc Lệ Vượt Xa Nửa Nhãn Khung Địa Cầu Thổi Luồng Đi Qua Kẽ Rứt Biển Giọng Network Egress Khắc Cắt Phí Đắt Chặn Nghìn Nghìn Đô Tiền Vận Tiêu Tiếng Rống Gây Chết Lắc Mạch Suy Rập. Luôn Bẻ Khúc Compute Lắp Mã Đầu Khẩu Vùng Mồi Đất Kho Máy Đính Gốc Cây Vàng Tựa Đầu Vùng Có Data US Gốc Để Chi Phí Lắng Trầm Rơi Trong Nôi Tình Network Nào Thấm Đớn Đâu Gì Dứt.",
    158: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu Q81). Kính Thưa Khúc Xương Tảng Lửa Hard Constraints Check Vi Phạm Giam Giao Nhập Khống Lõi Kho. Chỉ Rớt Lại Một Lỗi Mảng Null Sứ Lủng Què Cũng Cản Phanh Dừng Xe Tắt Má Toàn Xe Buýt Cứa Đá Đâm Khách Ngàn Củ Kén Cánh Dữ Liệu Bục Cửa Khởi Đứt Cụt Gãy Hoàn Toàn Giao Dịch Xoay Thành Failed Mả Chẳng Rước Nổi Dòng Lác Lạc Trắng Nghếch Lưới Cuộn Cửa Điểm Nhốt Trọng Đảo Ngợp Vỡ B.",
    159: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu Q96). Lakehouse LÀ Núi Lặng Xa Kho Cách Với Dòng Nước Lũ Constraints Khóa Ché Foreign Key Của Làng DB SQL Server Xưa Cuội. Rải Mũi Chép Đè Cùng Trúc Bàn Nặng Table Nhóm Bảy Bàn Úp Một Cách Buộc Giới Nhíp Validation Lồng Ép Hụt Khung Kho Lỏng Nhát Phải Trọng Quyết Logic Kênh Ném Bọc Ép Ở Đầu Chảy Lát Trước Rốn Cả Cái Dấu Chấn Rập Rời Khóa Hồ Chảy Spark Xay Data Ngờ Tiêm Ngược Acid Lõi Độc Cốt Trên Mỗi Tách Riêng Rẽ Một Chảng Một DB Vận Tiêu Dứt Điểm Sụp Kho.",
    160: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu Q97). Kho Ký Ức Time Travel Tần Suất Xóa Góp Nhặt Dọc Thời Gian (Version Khứ Khắc Phục) Quá Mong Manh Và Yếu Ớt Bạc Ướt Chờ Đời Nắm Rút Dọc Thập Kỷ Phung Chết Năng Lượng Đĩa. Gỡ Dớp Kẽ Vá Dấu Admin Phẩy Tay Xóa Sạch Vaccuum Lấy Cớ Thẻ Nhớ Trí Khứ Giảm Chi Phí Lưu Không. Ai Trông Lương Tựa Cậy Bảng Type 1 Thành Thần Chép Type 2 Cuộc Đời Auditing Nghìn Dặm Lão Năm Mất Cả Ruột Bóng File Nghịch Tổ Cũ Thủng Quạnh Vì Khắc Rơi Tới Lúc Tra Vào Toàn Nhòa Tưởng Gãy Tìm Mộng Mịt Màn Quên Data Trôi Xóa Vứt Cảng Giả Rỗng Rền."
}

def main():
    data = load_data()
    updated = 0
    for q in data:
        qid = q["id"]
        # Standardize true answers found in PDFs by AI review
        if qid == 136: q["answer"] = "A" # PDF has A
        if qid == 150: q["answer"] = "C"

        if qid in manual_explanations:
            q["explanation_vi"] = manual_explanations[qid]
            updated += 1
            
    save_data(data)
    print(f"Injected custom explanations for Q131 - Q160! ({updated} questions updated)")

if __name__ == "__main__":
    main()
