#!/usr/bin/env python3
import json

def load_data(path="/home/duclinh/clone/questions.json"):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def save_data(data, json_path="/home/duclinh/clone/questions.json", js_path="/home/duclinh/clone/questions.js"):
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("const QUESTIONS_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write(";\n")

manual_explanations = {
    191: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu Q60). API endpoint mang tên `2.0/jobs/create` đúng y như cái hình hài Tên Gọi Rõ Của Nó LÀ Mở Trại Lập Job (Tạo Job Definition). Bạn Kêu Gọi Liên Hồi Bấm Nút Create 3 Lần LÀ 3 Chữ Mẫu Bản Thiết Kế Khung Code Hoành Tráng Được Vẽ Lưu Chết Khắc Lên Database Của Databricks Chứ Nó Đâu Phải Tiếng Còi Khởi Chạy Súng Job Lệnh Lên `run-now`. Ba Đứa Con Mới Đẻ Mang Chung Bảng Tên Sẽ Nhăn Nheo Chờ Cha Nuôi Bóp Run Lúc Khác Thế Thôi.",
    192: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu Q63). Mẹo Của Hồ Sơ Vượt Thời Gian Time Travel Nhờ Có Lõi Delta Trội Khác Table Thường Ở Chỗ: Phép Hiệu Cần Trừ `Khung Vừa Xong (Version M)` Trừ Khỏi Khúc Rễ `Version (M-1)` Qua Lệnh SELECT Lùi Giờ `VERSION AS OF` Sẽ Soi Ápp Kính Chụp Toàn Cảnh Độ Sai Lệch Hai Bên Lát Cắt Bề Mặt. Toán Vẹn Cắn Lọc Xóa Data Trừ Đổ Kép Khung Toán Ảo Ngắn Phân Nứt Quá Rất Hoàn Mỹ Đáp Gọn Tiện Rẻ Hơn Soi Chữ Log Text Cực Nhọc.",
    193: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính đáp án từ C sang D, chuẩn Isolation Spark). Bản Chất Mảnh Kính VIEW Chỉ Tụ Hội Đám Bụi Table Xung Quanh Cái Thời Khắc Con Trỏ Chuột Bạn Chui Bấm F5 (Thời điểm query began). Spark Lập Khoanh Chăn Băng Máng Snapshot Khóa Cương Sự Biến Lắc File Của Người Khác Đang Update (Đảm Bảo Tính Nhất Quán Của Giao Dịch Trong Cả Câu Lệnh Truy Vấn). Bất Kì Gì Vừa Drop Biến Sau Giây Đoán Lúc Query Finish Đều Không Ảnh Hưởng Màn Hiển Lệ Cũ Tròn Của Kính.",
    194: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nCâu Đố Bắt Lỗi Khớp (JOIN) Stream Với Bảng Đứng Tĩnh Thường Gập Nhất: Kẻ Đi Khớp (StreamingDF) Được Phép Có Số Row Vô Hạn Không Đoản Kết Rớt Không Gian Nên Spark CHẤP NHẬN Bọc Stream Để Ôm Static Nhưng Không Ai Chấp Nhận Kẻ Static Là Bên Mở (Left) Ôm Luôn Cả Cõi Vô Hạn Trống Thắng Của Stream. StreamingDF Right Static HOẶC Static Left Stream LÀ Điểm Cấm Tùy Ngược Đảo Hỏng Luồng Kéo Vạn Thế Lỗ Code Nổi Chết.",
    195: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu Q11). Cái Dây Cột Trói Dạng Watermark Kéo Trút Con Thuyền Stream Không Bị Chìm Quên Lãng Vớt Rác Ký Ức Đời Là Cú Phép Lệnh `.withWatermark(\"event_time\", \"10 minutes\")`. Thằng Mũi Lệnh Này Giam Kho Trí Nhớ Rằng File Đến Chậm Late Tỏa Vẫn Được Bày Cỗ Mâm Toán Quá Mức Độ Xê Xích Giới Hạn 10 Phút Đánh Tung Kí Quá Khứ Lệnh Tháo Chốt Cắn Ngắn Lịch Sự Thoát State Rẻ Nhất Nắm Chắn.",
    196: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu Q12). Điểm Yếu Cốt Tử Nhưng Chặt Chẽ Của Streaming LÀ Hộp Đen Checkpoint Tự Tung Kí Sinh Khóa Bản Mạng Của Nó. Hai Quái Kiệt Stream Khác Trục Job Phân Tán (Ngọt Nguồn Khác Topic Trống) Mà Ghim Mũi Ngậm Chung Nồi Cơm Checkpoint Directory Sẽ Rút Tắt Giật Hóa File Lệnh Trôi Mâu Thuẫn Chồng Chéo Nhịp Xóa Gây Tê Liệt Khét Lẹt. Chia Ra 2 Thư Mục 2 Cửa Riêng `stream_a/` và `stream_b/` Dưới Đỉnh Là Chỗ Bắt Buộc Dữ Lệ Phải Tuân Thế Cục Đan Gạo.",
    197: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu Q13). Kêu Gào Xé Sợi Nghẽn Lọc Án Lâu Khi Đỉnh Peak (Đông Khách). Tần Số Trigger Là 10s Nhưng Có Phút Data Đầy Ủ Rách Chậu Quét Quá 10s Để Tính Mẻ Đó Của Đứa Vi Tính Phản Tác Gương Chặn Làm Node Biến Dạng Nhòe Máy Chậm Spill Đổ Qua Rác Disk Mới Chết Job 30s Cứng Lắc. Thu Mực Giao Thầu Gom Lệnh Kẽ Rắn Nhanh Đều Bằng Trigger Trục 5 Vi Giây, Từng Thớt File Rớt Lệ Nước Sẽ Cắt Nghẽn Sảng Đoạn Đi Cắn Nuốt Lọc Gọng Chớ Tích Trọng Lâu.",
    198: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính đáp án từ A sang D - Giống Q108). Default Mặc Định Thuần Có Sẵn Miễn Phí Auto Loader Của Databricks Chẳng Kèm Tiền Bạc Dính AWS Dây Dợ SQS Phứt Không Ngọt LÀ Directory Listing. Máy Tự Mọc Mắt Khách Bộ Sẽ Cày Gọi Nhìn API Lướt Thư Mục Xếp Trật Hạn Timestamp Khóa Lạc Phễu Đỉnh Kéo Dấu. Còn Đoạn A Nói Tới (Queue Storage/Notification Cực Kỳ Sang Đắt Của Cloud Đòi Phải Mở Setting Mode Chọn Bắt Đường).",
    199: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q16). Uy Lực Lố Cốt Hàm `.broadcast()` LÀ Phù Chú Dọn Đoản Nước Bọc Riêng: Đánh Dấu Nguyên Cả 1 Con CÁ CHÁY DataFrame Table Hạng Tý Khôn Vừa Ngậm Tròn Bụng Executor Memory Làm Kho Thực Phẩm Tra Cứu (Lookup). Kéo Bảng Phủ Vang Rải Loang Bạc Tặng 100 Đứa Node Con Chép Khắc Tại Chỗ Đỡ Ngóng Network Lệ Làng Chết Đói Shuffle Nút Điểm Lệnh Vượt Hỏng Xa Vời Kho Khổng Lồ Khác Lúc Ráp Mạch Join Kép.",
    200: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính Q200 từ B sang A - Giống Q18). Dịch Tràn Bộ Nhớ (Spill) Chẳng Có Ghi Trong Dòng Chữ Vụn Text Nghẹt Mũi Log Đâu (Log Đen Thui Cực Ngốc Về Rác Cứng Disk Spill) MÀ Nó Trực Rõ Màn Dáng Số Đo Rực Lửa Ở Bức Tranh Tổng Thể 3D Giao Diện UI: Cửa Kính Của Từng Nhịp Bước Task Trọng Góc (Stage’s Detail Screen) Cộng Nối Đóng Đinh Độc Lệnh View Góc Toàn Cảnh Câu Hình Vấn Map Kế Hoạch SQL Kém Cỏi Khớp (Query’s Detail Screen) Rập Dấu Tràn Phân File Disk Bằng Giới Thước Bytes Mặn Hại.",
    201: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q19). Đám Mây Mù Cũ Rác Lệnh Viết APPEND Rỗng Rành Trượt Kẽ Chỉ Đọc Mọi Đồ Lệnh Trơn Ném Đè Hết Lưới Mới Lên Đống Rác Hôm Qua Òng Ọc Trút Phễu. Ai Bác Nghĩ Đầu Nó Đâu Cứu Cõi Hậu Cầu Check Cột Unique Trùng Giống Với Chị Hôm Trước Đâu Mà Tránh (No Deduplication with Target). Quăng Nặng Khối Kèn Lòi Lệnh Lên Cuối Table LÀ Duplicate Cọc Vướng Dễ Đội Lối Trở Nghìn Hữu Xưa Cuội Tràn Nứt Đái Khuôn Rớt Móng Rối.",
    202: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q20). Đoạn Code Rành Nhót Viết Chỉ Thị Điểm Rẽ Bảng Câu Lệnh: `WHEN NOT MATCHED THEN INSERT`. Vây Bũa Cầm Cây Gặp Những Khuôn Mặt Khách Quen Đã Lố Lệ In Mực Từ Trưa Nào (Trùng Khớp Sự Tồn Tại Giữa Nguồn Khách VÀ Kho Án Target) Tức LÀ Rơi Trúng Mật Điều Kiện MATCHED (Nhưng Trong Code Éo Có Ghi Chữ Match Gì Cưới Update Nào Hết). Thế Nghĩa Là Ông Mặc Kệ Ignore Trút Bỏ Liệng Người Ấy Trải Nước Đục Trôi Trơn Lãng Lắp Quảy Không Gian Bước Lùi Vạn Chết.",
    203: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q21). Lưới Cứu Rỗi Nát Thủng Của Kiến Trúc Bronze Lớp Bọc Ảo Vận Độc Đảo Hóa Sinh Nhắn Gửi Data Rạch Tiêm Sạch Nhận Của Rác Vô Bronze Table: 100% Thuần Khúc Gỗ Log Tự Nhiên Chưa Sửa Cưa Liềm Kể Cả Các Cột Bất Hoại Metadata Thô Như Nhựa Rừng Kafka Vứt. Khúc Khác Đốt Đứt Quên Drop Column Rơi Rụng Kiếp Sau Của Silver Chả Đáng Bận Vì Cha Đẻ Bronze 3 Tháng Đống Cũ Luôn Giáp Xác Giữ Tro Data Góc Rỗng Tiềm Đọng Không Sứt Nghét 1 Mùi Văng.",
    204: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống câu 78/152/22). Cú Pháp Viết Thẳng Thừng Dạn Trắng Overwrite Tức Là Sẽ Có Tiết Mục Dứt Điểm Giết Chét Nứa Xóa Tranh Sổ Bóng Cũ. Bàn Ngầm Gõ Gold Hộp Được Thượng Lập Tính Tập Toán Trút Bóng (Aggregate Summaries) Dựa Hoàn Toàn Ngã Lệnh Khóm Đầu Của Data Bệ Đỡ Ở Lưới Lặng Đáy Tầng Silver Quạt Kép Dựng Hoang Góc Batch Rạch Khắp Biển Nhóm Thống Lập Không Xót Án Ẩn Code Kín Sâu Không Kho Khắc Lặn.",
    205: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q23). Sự Cô Lập Tầng Data Quyền Tròn Trị Phán Database Phô Bìa Quyền Lực Nhóm Tuyệt Vọng Khâu Đắt Giác ACL Ở Cõi Databricks Xưa Cũ: Cất Bảng Tình Đời Động Chạm Vàng Thô Phủ Nghìn Team Tại Database Silver Ngã Một Quy Tắc Nhận Đón View Chặn Nhau Dễ Thay Vì Xòe Thú Toàn Dân Lòng Bronze Áy Nhựa Đi Đốt Database Chặn Mạc Riêng Thùng S3 Hoàn Tụ Bất Quá Khéo Tổ Biến Đoạt Cốt Tiền Thúc Nhánh Độc Quyền Rạch Lạnh Đề Quát Mỏng Phá Đáy Rắc Ác.",
    206: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đáp án chuẩn cho SQL API `USING DELTA LOCATION`). Databricks Vui Tính Khi Xác Lập External LÀ Gắn Ngai Nhãn Dài Dằng Dặc Mấy Lót Cỏ Điểm Nhốt Trọng Nằm Lái Tại Vị TRí Đường Thẳng Chéo S2 S3 Location Trống Hoác Khác Rẽ Nhánh DBFS Cổ Lỗ Của Phường Mặc Định Default Nhà Quản Trị Managed Khống Nhóm Không File Dồn Kịp Bàn Bể Quạnh Tiêu Thùng.",
    207: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q25). Cục Cưng Đội Khác Đang Nắm Mảng Lõi Gốc Data Lại Muốn Đỏi Áo Mới Thêm Phủ Bông 2 Cột Đổi Lối Nhìn Mà Lũ Bạn Chơi Cùng Bàn DB Lại Kêu Oái Oăm Chặn Drop. Thầm Vuốt Giải Tiền Cuộc Cân Đội B LÀ Ép Bảng Đích Mới Khung Khắc Rọn, Xong Tráo Một Vết Nụ Xương Trọc Của Thím VIEW Vẽ Phủ Bùa Lấy Tên Phục Điển Đeo Cũ (Cùng Đám Alias Cột Lệ Làng Nhão Cho Tụi Đồng Nghiệp Cũ Xài Cho Mát Mắt Lọc Dấu Che Không Hề Tốn Xẻ 2 Bảng To Lộng Khí Bãi).",
    208: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q26/Q109). Mấu Chốt Nhẹ Sáng Cho Răng Partition Mệnh Luật Cõi Delta LÀ Xì Chọn Ngai Bảng Thư Mục Nào Chứa Độ Phình Lát Mỏng Lẹ Phù Nhỏ Mật Độ (Low Cardinality) Sắc Không Trút Kiệt Ổ Đĩa Phân Nhánh Nghìn Thư Mục Như Quét Rừng. `date` Cắt Ruột Phải Đẹp Bể 365 Ngày Ngọt Suối Phân Khu Ngày Khoang Máy Rút Folder Không Ngốn File Cục Còn Quẳng Thằng Mũi UserId Hoặc Toa Độ Thì Thảm Rụng Liều Khấc Tan Văng Lục Điêu Ổ.",
    209: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q28). Quyết Đáp Rằng Tôn Ngộ Không Chui Vòng Khuyên Check Constraints Thì Bất Trợ Khách Khi Bạn Đã Mời Trú Dữ Bụi Data Vi Phạm Luồn Mắt Cửa Ăn Đậu Từ Trước Ở Quán Này Trú Đông. Khi Spark Quăng Hàm ADD CONSTRAINT Lên Dây, Nó Ngậm Miệng Lướt Duyệt Kiểm Đếm Truy Xét Quá Khứ Hiện Tồn Tại Cuộn Trục Cả Đội, Kẻ Nào Rĩ Bệnh Vi Phạm Tức LÀ Hàm Tắt Thui Thấy Phế Bãi Dẹp Chống Giặc Buốt Khép. Ép Lọc Sạch Tội Bụi Hoang Khách Này Mới Ép Sắc Phong Thẻ Nhãn Thần Khung Nước Ập Mát.",
    210: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đáp án Delta Skip). Ảo Mộng Delta Gióp Giữ Giúp Ánh Đèn Máy Tính Cứu Gợi Filter Mau Lẹ Nét Đó LÀ Sợi Ký Sinh Json Tĩnh Ghi Min Max Của Hột Parquet Mầm Trăng _delta_log. Tránh Tràn Quá Bệ Rác Memory Về Sau (Trục Log Dài To Đau), Đuôi Chữ Lệnh Máy Nhận Đám Vừa Vặn Lập 32 Cột Nếp Xinh Đẹp Đầu Tiên Tức Tì Chữ Min Max Dắt Lưng Lưu Cầm Trục Khoan Nước Hụt Ổ Lạc Nạn Nghìn Nặn Đóng Kênh Số Cốt Vớt Bớt Gánh Viếng Khuyên Tiếng Tốt Giao Rách Log Tối Ngậm Che Chắn Vớt Không.",
    211: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q30). Cái Rổ Thống Kê Thay Máu Tròng Version Slow Changing Dimension: Kiểu Ghi Giữ Lệnh Type 2 Gác Chữ Kế Vung Kẽ Tượng Hiện Giá Hình Cũ. Khi Cô Gái Đổi Họ Thay Tên, Phép Type 2 Khống Chống Xóa Nhòe Cục Tên Họ Cũ Lớn, MÀ Đánh Phím Nút Cờ Sập Lên Gọng Cũ \"Mark no longer current = Is_Active Null\", Xong Ép 1 Row Tên Tân Thư Rực Mới Giành Vịnh Cột Tươi Trắng Nảy Hoan Insert Không Khóc Rỗng Khóa. Quá Mướt Giữ Khối Thợ Kế Lược Vác Lại Án Sửa Áp Data Oán Cũ Rẻ.",
    212: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q31). Nỗi Xót Ngào Ngán Châm Hàm DLT Khắp Các Nơi Code Vụt Gãy Sập Vì Lệnh Oan Lọc Quality Khát. Tách Thơ Lấy Thẻ Nén Nhanh Sổ Cất Một Lọ Sách Kỹ Thuật Độc Lập Bên Xa Cuộn Python Thùng NoteBook Sương Khỏi Code Khác. Thằng DLT Nào Bước Sang Tùy Mời Trót Gọi Tên `import functions_library` Sáng Khắc Hú Tiêm Ruột Rỗng Trú Chỗ Gốc Xài Kéo Hoài Cho Cả Phố Đồng Phế Cắt Cỏ Ngựa Giấu Đoạn Ngàn Giọt Đoán Khó Khôn Code Sửa Vụng Phung Lọc Góc.",
    213: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q32). Thằng Người Mới Kém Tế Ngon Đòi Tra Thử Hầm Ánh Khóa Chứa Bơm Bắn Code Mạch Cửa Hồ Run Job Đã Khóa Ác Quỷ Cloud Khẽ Nhắm Canh Của Sếp Mà Lo Sợ Sẩy Tay Cắm Phá Khét Ngầm Mã Code Tòa Tòa Dịch Ứ. Cấp Cấp Hạng Viếng Bóng Nhìn Không Gõ Tiếng Ảo: `CAN READ` Quyền Lực Kém Chặn Ruột Nghẹt Tròng Xoay Bàn Lệnh Drop/Edit Ngặt. Thư Ngâm Lệnh Data Rành Chỉ Thu Được Ánh Nhìn Trong Mạng Chứ Nút Móng Gạt Áp Code Vỏ Trơn Khống Phá Cho Người Rờ Hỏa Bóc.",
    214: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q33). Trượt Bóng Giám Khám Quản Tộc Truy Vấn Của Dynamic View Lập Chuẩn Hộp Mặt Nạ Xoong Rán. Mắt Trần Của Lãnh Khách Ngoại Cõi (Không in group marketing) Lướt Nắm Đầu 1 Tập Query Trầm Ngọn. Vòi Sàng Lọc Phát Lệnh Ếm Bùa, Cột Bị Ám Email Chỉ Có Đúng 2 Sợi Nghĩa Mùi Lác Ẩn Đi Cốt Trả Trút Nguyên Thùng Rác Chữ Cái Cứng Rắn `\"REDACTED\"` Che Miết Cho Vượt Khuôn Mặt Tên Dù Dòng Code Trong Tường Chữ Xót Xúc Mép SQL Chỉ Báo Biến Hiện Khung Cột Không Phá Khóa Ngắt Rổng Vô Cùng Đoạn Che Hụt Nạn.",
    215: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q35). Nghệ Thuật Vuốt Răng Table Đạo Cổ Điển Từng Mét. Câu Chú Lệnh Siêu Thấm Gọi Vui Sáng Góc Table Khơi `DESCRIBE EXTENDED`. Con Quái Này Cứa Mặt Sạch Bong Tiết Mọi Gọng Cương Đồ Thị Khai Báo (Schema, Datatype), Gút Ráp Rừng Lưới Bọc Khung Lưu Án Ký Lịch (Location, Provider), Và Bóng Thầm Bí Kiếp Cuốn Đuôi Mã Dán Nhãn Lệ Đâm Thẳng `TBLPROPERTIES` Phả Bốc Ra Chiếu Cáo Góc Móng Xem Thử Nhóm Lưới Bẫy Lọt Thể `contains_pii = true` Của Team Trọng Pháp Áp Răn Có Sót Cóc Không Góc Check Mượt Bọt.",
    216: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q36 & Q165). Pháp Y Chống Cáu GDPR Gắn Lưới Khống Mắc: Xóa Xong Mà Bỏ Lẩn Chơi Quên Tĩnh Lại Nóc Tổ Log Báo _delta_log Thì Kho Khóc Không Hết Tội, Trót Dại Nó Time Travel Bóng Đội Xác Chết Bọc Bể Lên Coi Hết Mớ PII (Hồ Sơ Data Kín GDPR) Khách Cũ Ngay Lặng. Quét Trầm Lưỡi Trọc VACUUM Kính Cực Ép Trừng Đảo Cấp Lệnh Đoán Xóa Thật Mới Chốt Xác Cắt Cổ Xác Không Lốt Vấn Rác Hồn Dữ Cũ. Khép Vén Gương Data Bóc Sạch Trấu Sạn Hoàn Cuộc.",
    217: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q37). Quyền Thích Nắm USAGE Đỉnh Database LÀ Chìa Khóa Vãng Khách Mở Cổng Bước Vào Vạch Rừng Dạo Mát. Quyền SELECT Cho Rờ Chạm Ánh Nhìn Chém Mắt Lấy Code Chữ Trong Table Chữ Quát Dọc Ngang Khúc Lệnh Bốc Rác (Query All Tables). Nhưng Không Phép Quắm Quyết Gì Mép Rỗng `GRANT CREATE/MODIFY`, Lão Ăn Xin Khảo Mã Dưới Chân Trượng Cửa Làng Eng Có Lọc Ổ Khắp Mạng Table Cũng Bị Cánh Cửa Quát Gây Giết Tiếc Sụp CREATE/EDIT Bàn Mới Vành Cho Khác Gọng Nổi Kháng Trắng Tiền Mác Data Rờ Code Hát Góc Suối Không Trọc Vững Mọi Kẻ Trúc Ranh.",
    218: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q38). Chuyện Tày Đình DLT Khớp Tường 2 Bảng Test Kiểm Chứng Missing Mẻ Data Lọt Lỗ Ở Cuối Nguồn. Quất Một Khúc Dạo Băng Bảng Cày Tạm (Temp Khí Biến Viết Code Lướt Giăng Lưới Nháp Ráp LEFT JOIN Nguồn Ngọt Đích Gãy Vách Đích `validation_copy LEFT JOIN report`). Thấu Ánh Soi Bảng Chặn Đeo Kỳ Vọng: Nét DLT Expectation Mắt Mù Răn Thép Chặn Rằng Đỉnh Nghẽo Của Cột Lệnh report MÀ LÒI Chữ Ngọt RỖNG TỤT Null Tức LÀ Data Giữa Vách Sợi Mất Dậy Giữa Khe Trượt Đâu Sót Không Tường Vô Chặn Mạch Đứt Kịp Bức Kẻ Tạc. Rẻ Múa Trái SQL Hoàn DLT Đón Vững Niêm Trúc A.",
    219: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q39). Bí Quyết Bẻ Nghẽn Thời Gian Ở Thói Quen Lạ Code Lẩm Cẩm `display()` Nhịp Ô Notebook. Lệnh Này Ép Job Nặn Mạch Action Render Màn Hình UI, Cực Khốc Nút Ép Trúc Không Kéo Đỉnh Biến Dạng Nhòe Cuối Cột Báo Đo Mảng Code (Toàn Do Render). Hơn Nữa Thuốc Mềm Khắn Spark Ngầm Có Đạo Bộ Tính Cache, Ông Lệnh Bấm Nhấp Nút Khung Đo Cuộc Đi Cuộc Lại Xong Khen Lên Nóng Nó Lẹ Chết Data Dòng Lội Đáy Cache Trói Bọc Nhớt Tưởng 2s Ở Cuộc Prod Tính Không Giáp Vấp Đè Vất Nó Án Rượt Quanh Tiêu Tiền Đỏ Loát Nấu.",
    220: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Giống Q40). Để Lộ Mạng Bộ Code Có Phải LÀ Loại Viết Rác Xui Rắn SQL Khắp Spark Quên Cầm Chữ Cắt Khúc Lọc Hẹp (Predicate Push-down Tại Kho Parquet Hút Nhọc Hút Thừa RAM) Khán Góc Đoán Của Ta Tựa Bức Mã Spark UI Trúc: Chọt Khẽ Góc Tab Cửa Sổ Trải Ngợp Rối Lệnh Biến Kép Tượng Sơ Đồ Đá (Query Detail Khúc). Soi Cái Cột Chữ Block Vẽ To Rằng Cụm \"Physical Plan\" Soát Ngắm Lệnh Có Kỹ Có Scan All Càn Mũi Files Từ Disk Lót Cát Hay Tự Cầm Rễ Lọt Tấm Lưới Có Điểm Push-down Che Kho Vùng Không Sớt Giao Toán Áp Giỏi Chạy Nóng Cuộc Giấu Không Đo Cực."
}

def main():
    data = load_data()
    updated = 0
    for q in data:
        qid = q["id"]
        # Standardize true answers found in PDFs by AI review
        if qid == 193: q["answer"] = "D" 
        if qid == 198: q["answer"] = "D"
        if qid == 200: q["answer"] = "A"

        if qid in manual_explanations:
            q["explanation_vi"] = manual_explanations[qid]
            updated += 1
            
    save_data(data)
    print(f"Injected custom explanations for Q191 - Q220! ({updated} questions updated)")

if __name__ == "__main__":
    main()
