#!/usr/bin/env python3
import json

def load_data(path="/home/duclinh/clone/questions.json"):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def save_data(data, json_path="/home/duclinh/clone/questions.json", js_path="/home/duclinh/clone/questions.js"):
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("const QUESTIONS_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write(";\n")

manual_explanations = {
    11: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nLệnh VACUUM dùng để xóa vĩnh viễn các tệp dữ liệu không còn được tham chiếu (như các bản ghi đã bị DELETE) và cũ hơn một khoảng thời gian giữ lại ấn định (Retention Threshold). Tuy mặc định Retention của Delta Lake là 7 ngày (168 giờ), nhưng nếu lệnh VACUUM kích hoạt và xóa tệp thành công, khả năng Time Travel về dữ liệu đó sẽ biến mất lập tức. Câu hỏi ngụ ý VACUUM Job được hẹn giờ chạy vào 3am Thứ Hai (tức 26 tiếng sau khi chạy Delete job lúc 1am Chủ Nhật), nên dữ liệu bị xóa chỉ có thể khôi phục qua time travel trong khoảng thời gian ~24 tiếng này.",
    12: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nEndpoint Databricks REST API `2.0/jobs/create` chỉ có chức năng ĐỊNH NGHĨA (Define) một Job mới trong Workspace, đăng ký tên và các cấu hình liên quan. Nó KHÔNG tự động kích hoạt (execute) Job đó. Để định nghĩa và chạy ngay lập tức, người ta mới dùng endpoint `2.0/jobs/run-now`. Vì vậy, khi gửi request 3 lần vào `/create`, hệ thống sẽ tạo ra 3 Job Definitions mới tinh mang tên \"Ingest new data\", nhưng không có Job nào được chạy.",
    13: "✅ Đáp án đúng: E\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nYêu cầu bài toán gồm 2 vế: (1) Lưu trữ toàn bộ lịch sử các luồng thay đổi (Audit Logging) và (2) Cung cấp bảng phân tích chỉ chứa số liệu mới nhất (Analytical). Cách thiết kế Lakehouse chuẩn nhất là viết toàn bộ log thô (insert, update, delete) nhồi vào một bảng Bronze để không mất dữ liệu lịch sử. Sau đó từ bảng Bronze, ta dùng lệnh `MERGE INTO` để quét các pk_id và chỉ cập nhật (hoặc xóa) các bản ghi mới nhất vào bảng Silver. Bảng Silver lúc này chính là trạng thái \"hiện tại nhất\" của dữ liệu, đạt yêu cầu phân tích.",
    14: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nViệc lọc (Filter) các bản ghi trong `account_history` có giá trị `last_updated` và `last_login` ứng với giờ gần nhất giúp ta khoanh vùng được những Account nào đã phát sinh giao dịch/sự kiện mới. Sau khi tìm ra được trạng thái (phiên bản) mới nhất của từng User ID, ta dùng cú pháp `MERGE` để Upsert (Insert/Update) vào bảng `account_current` (bảng Type 1 - Ghi đè trạng thái cũ). Việc này rất tối ưu cho khối lượng dữ liệu khổng lồ vì ta chỉ tính toán và Merge những Account có biến động trong 1 giờ qua, chứ không ghi đè lại toàn bộ triệu người dùng.",
    15: "✅ Đáp án đúng: E\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nThay vì dùng logic OVERWRITE (xóa toàn phần bảng và viết lại), việc chuyển qua MERGE INTO sẽ chỉ tác động tới những row có sự thay đổi từ nguồn. Tính năng `Change Data Feed` (CDF) của Delta Lake cung cấp khả năng track được chính xác row nào vừa bị Insert / Update / Delete ở lần Merge đó. Team Data Science chỉ việc đọc luồng CDF này ra và áp dụng model lên đúng những khách hàng vừa có biến động dữ liệu. Điều này giúp hệ thống khỏi phải chạy model cồng kềnh cho các User vốn không có data đổi tay trong suốt 24h.",
    16: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nKhi bạn dùng lệnh `CREATE OR REPLACE VIEW`, bản chất là bạn đang tạo ra một khung nhìn (cấu trúc logic ảo) chứ không phải lưu dữ liệu vật lý xuống đĩa (DBFS). Khung nhìn (View) này sẽ kéo và tính toán lại câu lệnh SQL bên trong (JOIN giữa bảng users và orders) dựa theo trạng thái bảng TẠI ĐÚNG THỜI ĐIỂM người dùng truy vấn Query (at query time). Nghĩa là, nếu bảng nguồn thay đổi thì View khi Query cũng sẽ lập tức cho ra dữ liệu nội suy mới nhất.",
    17: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nVới tính năng `Auto Compaction` (Tự động nén tệp) trong một luồng ghi Structured Streaming diễn ra liên tục (Always-on) kết hợp lệnh MERGE, lượng dữ liệu mới vào bảng (Bronze/Silver) sẽ nhỏ giọt liên tục. Để tối ưu tốc độ đọc-ghi nhanh, Databricks sẽ tự động điều chỉnh (autotuned) size mục tiêu của các tệp Parquet xuống mức nhỏ hơn (thay vì cố gộp lên hẳn 1 GB) nhằm giúp tiến trình Merge các file Delta nhanh gọn lẻ tẻ và không làm tăng độ trễ (latency) của luồng streaming.",
    18: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nKhi bạn chạy JOIN một luồng dữ liệu thời gian thực (Stream DataFrame) với một bảng tĩnh (Static DataFrame - thường nằm ở Delta Lake), tại ĐẦU MỖI MICRO-BATCH, Spark tự động chớp lấy Version (phiên bản) mới nhất lúc đó của bảng Delta Tĩnh để nạp lên thực hiện phép Join. Việc này giúp luồng Stream luôn được đối chiếu với Bộ Master Data (bảng tĩnh) cập nhật nhất mà không cần phải tắt/bật lại Streaming Job.",
    19: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nTrong PySpark Structured Streaming, để nhóm dữ liệu (group by) dựa trên khía cạnh Thời gian (Timestamp), ta không thể dùng `groupBy` thông thường mà phải dùng hàm Windowing. Cú pháp `window(\"event_time\", \"5 minutes\")` sẽ tự động chặt mốc thời gian thành các khung cửa sổ 5 phút không chéo lấn (non-overlapping / Tumbling window), gom các event rớt vào cửa sổ đó lại và tính toán `avg()` cho bước tiếp theo.",
    20: "✅ Đáp án đúng: E\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nThư mục Checkpoint (Checkpoint Directory) trong Structured Streaming đóng vai trò như \"sổ ghi nợ\" lưu trữ offset hiện tại (bản ghi nào Kafka đã đọc thành công) và file state. Nó TUYỆT ĐỐI không bao giờ được phép chia sẻ (share) giữa nhiều ứng dụng streaming song song nhau. Nếu ghi chung, luồng stream này sẽ ghi đè checkpoint của luồng stream kia, dẫn đến mất checkpoint và dữ liệu hỏng. Mỗi job bắt buộc phải có checkpoint folder cô lập, cho dù chúng cùng ghi vào 1 bảng Delta duy nhất (Đọc đồng thời vào Delta là hoàn toàn cho phép).",
    21: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nKhi độ trễ (execution time) của Micro-batch vào giờ cao điểm dao động vọt lên quá lâu (hơn 30 giây) so với Trigger mặc định (10 giây), việc hàng đợi stream phải duy trì cluster chờ đợi liên tục rất kém hiệu quả. Thay đổi cấu hình Job thành \"Trigger Once\" (hoặc \"AvailableNow\" ở bản mới) kết hợp với công cụ lên lịch (Scheduler) của Databricks Job chạy đều đặn mỗi 10 giây sẽ biến luồng Streaming thành các mini-batch. Mỗi mini-batch sẽ lấy hốt sạch lượng dữ liệu tồn đọng trong hàng đợi và xử lý dứt điểm, giảm hẳn chi phí duy trì trạng thái Idle cho hệ thống.",
    22: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nTính năng `Auto Compaction` (Nén tự động) trên Databricks là một Background Job tự khởi chạy ngay sau khi lệnh Ghi dữ liệu (Write commits) hoàn tất và sinh ra nhiều file nhỏ. Nó sẽ ngầm gom nhóm (OPTIMIZE) các khối file vụn vặt đó thành một tệp Parquet lớn hơn, chạy ẩn song song phía sau. Đặc điểm nhận diện của Compaction là kích thước đích tối ưu hướng đến sẽ linh hoạt tùy vào loại bảng, nhưng default cơ chế sẽ cố nén dồn tiệm cận quy chuẩn dung lượng (từ 128MB tới 1GB) để tăng tối đa tốc độ đọc cho Delta Tables.",
    23: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nCốt lõi (Programming Model) của Spark Structured Streaming cực kỳ đơn giản và thanh lịch đó là: Khái niệm \"Bảng tĩnh\" và \"Bảng luồng\" là một! Nó coi luồng dữ liệu trực tiếp đang được đưa vào (New data stream) y hệt như những dòng (rows) mới đang liên tục được gắn theo dạng APPEND vào một bảng cơ sở dữ liệu ảo vô tận (Unbounded Table). Nhờ mô hình này, ta có thể dễ dàng viết mã Dataframe / SQL cho Streaming hệt như cách ta truy vấn file CSV Batch.",
    24: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nKhi Spark đọc dữ liệu từ các file cục bộ/cloud để kéo vào bộ nhớ Memory tạo thành DataFrame, tham số `spark.sql.files.maxPartitionBytes` định nghĩa KÍCH THƯỚC GIỚI HẠN DỮ LIỆU TỐI ĐA (tính bằng byte - mặc định 128MB) được phép đóng gói vào bên trong một phân vùng Spark Partition đơn lẻ. Thông số này quyết định trực tiếp số lượng Task và kích cỡ cục bộ dữ liệu rải đều trong cụm tính toán ở chặng đọc (Ingestion Stage).",
    25: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nHiện tượng \"Skew\" (Dữ liệu bị lệch sóng) xảy ra khi dữ liệu của một/một số key tập trung dồn dập vào cùng duy nhất một Partition (ví dụ key \"Trạng thái: Hoàn tất\" đếm chiếm 99% tổng dòng). Hệ quả là Executor chịu trách nhiệm giải quyết Partition đó sẽ phải oằn mình làm việc lâu gấp cả ngàn lần (max duration rất cao) trong khi phần lớn các Executor kia nắm các partition ít dữ liệu nên chạy xong chớp nhoáng (min và median ngắn). Cả Job Pipeline sẽ bị nghẽn (bottleneck) và phải chờ task chậm nhất này.",
    26: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nHướng dẫn Best Practice cho Spark Shuffle / Wide Transformation (như GroupBy, Join) luôn khuyên KHÔNG NÊN nhồi quá nhiều CPU Cores vào chung 1 Executor duy nhất vì rất dễ gây ra tình trạng khóa luồng rác bộ nhớ (JVM Garbage Collection overhead) và I/O rớt mạng (network saturation). Giới hạn Vàng số Cores / 1 Executor để Spark chạy nhanh mượt thường nằm ở mốc 4 đến 5 Cores. Option B với (8 VMs * 20 Cores) có tính phân tán cao hơn nhiều so với việc bắt một máy gánh 160 Core cùng lúc (A), đồng thời RAM (50GB) không quá nhỏ để gây lỗi Spill như C.",
    27: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nViệc ứng xử ra sao với dữ liệu dính trùng `event_id` được quyết định bởi hành động (Action) viết mã DataFrame vào Database. Câu hỏi này nhắm vào chức năng của `MERGE INTO ... WHEN NOT MATCHED THEN INSERT` phổ biến trong Databricks, nơi mà các bản ghi mới có Key ĐÃ TỒN TẠI (trùng `event_id`) sẽ bị loại bỏ bỏ qua (Ignored) để không gây trùng lặp, còn những bản ghi mới chưa hề có dấu vết thì mới được Insert.",
    28: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nChange Data Feed (CDF) phơi bày ra toàn bộ dòng mô tả Lịch sử CRUD của mỗi hàng (Insert, Update_Preimage, Update_Postimage, Delete). Nếu kỹ sư CHỈ DÙNG LUẬT APPEND (Nối đuôi thêm) toàn bộ Output từ bảng bật rãnh CDF sang target table mà không có bất kỳ lệnh gạt bỏ/Merge nào, thì mọi chỉnh sửa của một ID (ví dụ 1 order được khách báo Đổi địa chỉ 5 lần) đều sẽ bị vứt thẳng vào Target Table thành 5 Row khác biệt trùng ID. Điều đó gây nhiễu và đẻ ra hàng loạt dư thừa trùng lặp (Duplicate Entries).",
    29: "✅ Đáp án đúng: E\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nKiến trúc Bronze (Raw layer) của Medallion Lakehouse yêu cầu Ingestion trực tiếp và KHÔNG ĐƯỢC PHÉP CHỈNH SỬA / MẤT MÁT nguyên bản dữ liệu đổ từ luồng ống gốc. Kể cả khi logic Silver layer (Do App lỗi code) vứt nhầm 1 field rất quan trọng, toàn bộ JSON payload gốc vẫn an toàn nằm vẹn nguyên tại bảng Delta Bronze. Chúng ta có thể quay lại đọc lại (Replay) vĩnh viễn dòng thời gian bằng cách viết lại Logic mới cho luồng Bronze -> Silver để trích xuất cái Field từng bị quên kia, xóa bỏ vĩnh viễn mối đe doạ data mất dạng sau 7 ngày trên Kafka.",
    30: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nTham số options `readChangeFeed` sử dụng để khai báo rằng hàm DataFrame nên truy vấn vào lớp dữ liệu bảng CDF (Change Data Feed) thay cho bảng tĩnh. Cho job chạy theo từng đợt hằng đêm (Nightly Job), thao tác đọc Batch (qua `.read.` của PySpark DataFrame) chứ KHÔNG PHẢI thao tác cấu hình Stream (.readStream.) là phù hợp nhất. Đoạn lệnh `spark.read.option(\"readChangeFeed\", \"true\").table(...)` sẽ fetch ra danh sách records đổi mới tính từ Version Delta được set.",
    31: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n`Schema Inference` (Dự đoán kiểu dữ liệu) tiện thì có tiện, nhưng rủi ro nhầm lẫn datatype là khổng lồ đối với JSON phức tạp lồng nhau chứa tận 100 Keys (Ví dụ: ID là String nhưng có đợt toàn số, Spark sẽ Inferred ra Long, làm gãy code đợt sau). Định nghĩa ép kiểu rõ ráng (Schema Declaration / DDL) ngay từ đầu cho bảng Silver cung cấp tính răn đe độ tin cậy của chất lượng dữ liệu (Data Quality Enforcement), loại trừ thẳng tay nếu kiểu json hỏng xó từ khâu Ingestion.",
    32: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nMã viết batch truyền thống với Dataframe `.write.mode(\"overwrite\")` là phương thức phá hủy-và-xây-lại. Mỗi lần đoạn mã Batch Job chạy, Spark sẽ mở 3 bảng nguồn lên đếm đếm Joined tốn rất nhiều công, rồi thẳng tay vứt (Overwrite) bản version cũ của `enriched_itemized_orders_by_account` để nhét toàn bộ đống dữ liệu tĩnh vừa Join xuống đĩa cứng. Cách viết thô sơ này không có tính Incremental, dẫu không có dòng dữ liệu nào thay đổi, nó vẫn hì hục Replace lại 100%.",
    33: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nPhương pháp tối ưu (Best Practice) quản trị kiến trúc Medallion Lakehouse là quy hoạch tách biệt MỖI LỚP (Bronze, Silver, Gold,...) THÀNH MỘT DATABASE riêng rẽ trên Databricks. Nhờ cấu trúc logic Database, người quản trị Workspace (Admin) có hể phân phối ACLs Access Control cực dễ dàng (VD: Data Scientist được read DB Silver, Marketing chỉ được dùng DB Gold), đồng thời Map ổ đĩa Cloud Storage vật lý chứa database cũng được băm chia theo tầng lớp an toàn.",
    34: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nBảng Managed Delta Table sẽ được Databricks tự cấu hình đường dẫn tới bucket default `/user/hive/warehouse`. Ngược lại, External Delta Table là Bảng trỏ tới một thùng chứa data (Azure ADLS, AWS S3) có địa chỉ tùy biến riêng của Data Team. Bằng việc chèn từ khoá `LOCATION 's3://my-bucket/path/to/table'` trong lệnh `CREATE TABLE`, ta ép Hive Metastore phải khai sinh bảng với loại tuỳ chỉnh External Table.",
    35: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nMục tiêu của bài toán: Cần bảng MỚI cho app mới, vừa phải đổi tên Field, vừa thêm Field mới. Nhưng bảng CŨ lại đang dùng bởi hàng chục Team khác (họ sẽ sụp nếu ta can thiệp đổi Column bảng này). Cách khôn ngoan nhất gỡ nút thắt Tương Thích Ngược (Backward compatibility) là: Phá bảng Aggregate cũ đi, định danh một bảng Delta Hoàn Toàn Mới chứa đúng data mới/Field Đổi. Bù lại, ta dựng nên một VIEW dùng TÊN và SCHEMA y hệt Bảng CŨ và select đổ ra từ bảng mới. Các phòng ban khác vẫn query vào View đó và hoạt động bình thường, không ai bị thương tích.",
    36: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nHệ thống tự tối ưu và bỏ qua phân vùng/tệp tin rác không chứa dữ liệu cần tìm là Data Skipping. Với mệnh đề `longitude < 20 & longitude > -20`, Delta Engine sẽ kiểm tra trực tiếp sổ log giao dịch Delta (Delta Log - Transaction logs). Quá trình đối chiếu các cột thống kê (Statistics) Min_Value/Max_Value chứa sẵn ở Log sẽ lập tức trả về cho Engine danh sách những files nào CÓ THỂ chứa kinh độ (longitude) khớp khoảng trên, giúp bỏ qua hẳn việc tải hàng ngàn Data files không liên quan lên bộ nhớ.",
    37: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nData Gravity - Dữ liệu ở đâu thì Máy Chủ tính toán (Compute VM Workspace) phải đẻ ra ở quanh đó. Nếu Cloud Storage Bucket chứa Data nằm trên AWS region Mỹ (US-East-1) mà Cụm Databricks Spark Workspace lại được thuê tại Data Center bên khu vực Ấn Độ (ap-south-1), thì việc Đọc-Ghi chéo lục địa đại dương sẽ đốt cháy một khoản phí băng thông mạng siêu khủng, kèm tốc độ trễ/Lag cực chậm. Do vậy Workspace bắt buộc đặt tại Mỹ dù Engineer ở tận đâu.",
    38: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nTrong Databricks phiên bản thời điểm kiểm tra, các ràng buộc điều kiện nội soi (CHECK constraints) đôi khi chỉ được hỗ trợ khai báo cùng thời điểm chạy lệnh khởi tạo sinh bảng (Initial Table Creation / CTAS). Việc bảng đã tồn tại sẵn, đã có data sau đó gọi `ALTER TABLE ADD CONSTRAINT` sẽ bị Engine chặn lại do khả năng cao không tương thích cơ chế kiểm định Schema Constraint cho hệ quản trị giao dịch có sẵn (trừ chức năng NOT NULL).",
    39: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nĐể đảm bảo quá trình Data Skipping qua Delta Logs File chạy với tốc độ tên lửa, Delta Engine giới hạn việc tự động tích luỹ thu thập dữ liệu thống kê min, max, count, nulls... CHỈ CHO 32 CỘT ĐẦU TIÊN (first 32 columns) của Bảng. Những cột từ 33 trở đi sẽ bị ignore (không thu gom thông tin Statistic) nhằm giữ cho File Checkpoint JSON của ổ Delta Log nhẹ nhàng và nhanh lẹ. Nếu bạn muốn thay đổi, bạn phải manual config `dataSkippingNumIndexedCols`.",
    40: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nĐặc tả kỹ thuật của bảng Slowly Changing Dimension (SCD) theo chuẩn **Type 2**: Lịch sử của Object được giữ lại toàn vẹn qua các dòng mốc thời gian. Bản ghi trị giá cũ sẽ KHÔNG bao giờ bị ghi đè hay xóa sổ (Overwrite), nó chỉ bị gạt biến cờ đánh dấu (Ví dụ `is_active = FALSE` hoặc Update `end_date = hôm_nay`). Sau đó, hệ thống sẽ chèn / INSERT thêm một Bản ghi dòng mới tinh chứa bộ Profile User mới, với cờ đính kèm là Active. Cách này làm Data To lên, nhưng bù lại ghi nhận hoàn toàn Timeline quá khứ."
}

def main():
    data = load_data()
    updated = 0
    for q in data:
        qid = q["id"]
        if qid in manual_explanations:
            q["explanation_vi"] = manual_explanations[qid]
            updated += 1
            # Adjust answers if they differ from the PDF
            # Example: 38 actually says B in JSON. We adapt.
    
    save_data(data)
    print(f"Injected custom explanations for Q11 - Q40! ({updated} questions updated)")

if __name__ == "__main__":
    main()
