#!/usr/bin/env python3
import json

def load_data(path="/home/duclinh/clone/questions.json"):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def save_data(data, json_path="/home/duclinh/clone/questions.json", js_path="/home/duclinh/clone/questions.js"):
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("const QUESTIONS_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write(";\n")

manual_explanations = {
    71: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính đáp án PDF: Đáp án thực tế là A). Khi Structured Streaming cần duy trì \"Sổ theo dõi\" (Incremental State) cho các luồng dữ liệu đến trễ (Late-arriving data) so với thời gian hiện tại, nó bắt buộc phải sử dụng cơ chế Watermark. Lệnh `withWatermark(\"event_time\", \"10 minutes\")` bảo với Engine rằng: \"Hãy giữ lại State của các bản ghi này trên RAM thêm 10 phút nữa đề phòng có mấy gói tin bị đứng kẹt xe tới trễ, sau 10 phút thì mới chốt sổ vứt đi để giải phóng RAM\".",
    72: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nKhi bạn thay đổi Logic Nhóm/Cộng dồn (Aggregates schema) hoặc số lượng Trường dữ liệu biến thiên trong Streaming, cấu trúc của File State nằm trong Checkpoint cũ chắc chắn sẽ sai lệch và gây Crash/Exception với cấu trúc mới. Cách duy nhất để đưa query nâng cấp này lên Production là xóa/chuyển vị trí `checkpointLocation` sang một mốc mới (Bắt đầu một vòng đời lưu State mới tính từ con số 0).",
    73: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nAPI gọi kiểm tra List/Fetch từ S3 hoặc ADLS (để hỏi Cloud xem: Ê có file nào mới rơi vào bucket không) bị các nhà cung cấp Cloud tính phí theo mỗi lượt request (Request Cost). Trigger mặc định nháy quá nhanh (chưa tới 3 giây/lần), khiến hệ thống call hàng ngàn API list rỗng không có data, mài mòn ví tiền. Bí kíp là căn theo đúng SLA 10 phút: Set Parameter Trigger bằng luôn `10 minutes` để nó tự kéo dãn tần suất gọi API, tối thiểu hóa Cost lưu trữ đám mây.",
    74: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính đáp án PDF sai lệch: Tính năng Broadcast dùng trên Memory, không dùng trên disk attached (C)). Lệnh `F.broadcast(dataframe)` là Cây cờ báo hiệu cho bộ phận Xếp lịch Spark (Tungsten/Catalyst) biết rằng: \"Ê bảng này nhỏ xíu kìa, copy & paste (Broadcast) nó phát thẳng xuống thanh RAM của TOÀN BỘ CÁC MÁY EXECUTOR đi, để lát Join với bảng lớn cho lẹ, khỏi phải giao tiếp chéo mạng (Shuffle)\".",
    75: "✅ Đáp án đúng: C\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính đáp án: Đáp án D trong dump xúi giục Full Outer Join rồi Overwrite là rất cồng kềnh - Đáp án chuẩn mực thiết kế Lakehouse là C). Thay vì Overwrite phá sập bảng, ta sử dụng Lệnh `MERGE INTO` để UPSERT dữ liệu. Bằng cách nối Merge Key, hệ thống sẽ đối chiếu với Table cũ: dòng nào Match (Key đã chui vào batch trước đó rồi) thì bỏ qua không Insert hoặc Update đè lên, dòng nào Not Matched (Mới toanh) thì hẵng chèn (Insert-only merge) chống lặp.",
    76: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nMột khi Data kỹ thuật (Metadata topic, offset, event_time) đã lọt qua lưới lọc vào yên vị trong bảng Bronze dưới dạng File Parquet vật lý, nếu sau này bạn vô tình Update thêm logic Cột Timestamp mới vào Script Streaming, Data CŨ trong cái Đống file Parquet hôm qua sẽ KHÔNG THỂ bay lùi lại thời gian để tự nhét thêm gán giá trị Kafka Metadata retro-actively (hồi tố) được. Tức là các dòng cũ sẽ vĩnh viễn mang giá trị NULL của các cột mới mẻ đó.",
    77: "✅ Đáp án đúng: E\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nCông cụ Databricks Auto Loader dùng Spark Structured Streaming làm lõi ngầm, nên cú pháp ghi luôn luôn là `writeStream` kèm thư mục sinh nhật ký tiến trình (`checkpointLocation`). Và để nó khôn khéo biết được khi nào JSON từ gốc mọc thêm 1 trường Field mới (Tự động biến đổi cấu trúc Schema), bạn bắt buộc phải truyền parameter `.option(\"mergeSchema\", \"true\")` để mở phím chốt an toàn gộp dồn Column mới vào Bảng Delta đích.",
    78: "✅ Đáp án đúng: E\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nThiết kế luồng Dòng chảy Aggregate Bậc Cao từ Silver (Sạch) lên Gold (Summarized/Aggregrations). Dữ liệu chảy từng ngày/từng giờ (incremental jobs) nếu làm truyền thống thì cứ xuất hiện 1 dòng mua hàng mới dưới Silver, Spark sẽ quét qua và Tính Toán Lại Toàn Bộ Tổng Lũy Kế Rồi Phủ Phanh Trắng Xoá bảng Dữ Liệu Cũ Của Cấp Bậc Aggregation Tương Ứng, tức là ghi đè Overwrite lại toàn bảng báo cáo (Trong TH không dùng cơ chế CDF / Merge Incremental).",
    79: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nTheo chuẩn 문 pháp SQL ANSI và Spark SQL, khi bạn xướng lên câu lệnh khai sinh bảng `CREATE EXTERNAL TABLE db.tableName LOCATION 's3://bucket/'`, từ khoá danh giá `EXTERNAL` đóng vai trò chốt hạ pháp lý báo hiệu cho Hive Megastore rắng: \"Tôi chỉ lưu tên ở đây thôi, chớ đụng rớt hay Drop file vật lý của tôi nghen\". Dẫu Databricks đôi khi ngầm hiểu Location = External, nhưng việc Code rành rành bằng Keyword EXTERNAL (D) mới là \"Đầu tàu\" đáp ứng chính xác yêu cầu quy chuẩn hệ thống Architect mandates.",
    80: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nPhân rã View (Khung nhìn) là một vũ khí ngoại giao tuyệt vời. Team Marketing sở hữu Bảng A có 50 cột (có 20 cột tuyệt mật). Team Sales cần coi Bảng A nhưng gọi tên Field bằng thuật ngữ rườm rà khác. Chiêu khôn ngoan nhất là Marketing sẽ chắp bút ra một câu lệnh `CREATE VIEW sales_view AS SELECT id AS sales_id, name AS cust_name FROM Bảng A`. Thế là Sales tha hồ coi dữ liệu realtime khớp schema chuẩn của họ mà chả rò rỉ đồng Data tuyệt mật nào, cũng tốn 0$ lưu trữ.",
    81: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính đáp án PDF: Đáp án D sai bản chất. Delta Lake Check Constraints là một Hàng Rào Chắn Rắn (Hard Constraint)). Nếu 1 triệu dòng Data tuông qua cửa Ải (Batch Insert) mà vô phúc tòi ra có ĐÚNG MỘT DÒNG vi phạm lọt ngoài Khoảng Lưới Limit (vd vĩ độ > 90 hoặc longitude ra 212.67), Giao dịch ACID sẽ Vỡ Mộng ngay lập tức. Cả Batch sẽ Failed đỏ lòm cúp điện cái rụp trên Log và KHÔNG 1 DÒNG NÀO CỦA CẢ LÔ ĐÓ ĐƯỢC LỌT VÀO BẢNG.",
    82: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nQuyền Hành Pháp \"Owner\" (Chủ Tịch) của một Job trong Databricks đính kèm gắn liền duy nhất với Thể Xác của con người tài khoản tạo ra nó. Hệ thống chặn đứng triệt để ý tưởng share chức vị Chủ Tịch (Owner Privileges) cho Cả một tập đoàn Group người dùng nặc danh để né rủi ro bảo mật tẩu tán Token. Nếu người cũ nghỉ việc, Admin Workspace sẽ phải thao tác gỡ tên ghép Owner sang hẳn trực tiếp 1 User cá nhân cụ thể khác.",
    83: "✅ Đáp án đúng: E\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính PDF: Partition chia ngăn vật lý theo Topic là hướng giải quyết triệt để nhất - Đáp án E). Bài toán có cả tá Dữ liệu mập mờ chui chung 1 bảng. Để Delete triệt cỏ PII của riêng Partition mang chuỗi nhận dạng 'registration', ta nên `PARTITION BY (topic)`. Về cơ chế vật lý thư mục Storage, lúc này Hive sẽ chẻ 5 topic vào 5 Thư mục rành rọt. Khi tới hạn 14 ngày dọn rác, ta chỉ cần Delete + Vacuum thả ga vào Thư Mục `topic=registration` thì phần tử PII rụng sách bạch, dăm Topic khác chẳng sứt miểng ngọc nà.",
    84: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính theo ngữ cảnh ACLs truyền thống: Lệnh GRANT USAGE (cho phép thấy DB) kèm GRANT SELECT (cho phép Đọc bảng)). Khi Kĩ Sư được ban phát bấy nhiêu đây ân huệ, họ chỉ nắm quyền đi Loan Quảng Mắt quanh database (lệnh SHOW) và Vọc đọc data (lệnh SELECT). Các hành động Táo báo Bạo loạn như CREATE (Lập bảng mới), INSERT (Bơm dữ liệu) hay DROP (Xóa nhầm DB) hoàn toàn bị Khóa Tay do chẳng có Lệnh cấp Quyền MANAGE hay MODIFY nào xuất hiện.",
    85: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính PDF: Nơi chứa sự kiện phình to - teo nhỏ cụm ảo là D). Công cụ Cluster Event Log (Nhật ký Sự kiện Cụm) hiện ra chễm chệ ngay TAB Event Ghi Trọng Trán cụm. Lúc Autoscale phình to Worker báo lệnh `RESIZING`, hay cúp rụp rớt Node do vắng việc `UPSIZE/DOWNSIZE`, Mọi diễn biến thay lốp thay vỏ Đều bị biên lai tường thuật phút giây cặn kẽ Tại ĐÂY chứ Ganglia chẳng đếm xỉa gì ba cái trò thay đổi kích cỡ tĩnh đó.",
    86: "✅ Đáp án đúng: E\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính đáp án Ganglia: Một cụm Node phân tán Xài Đắt Xắt Ra Miếng tức là Nút nào cũng Phải Vã Mồ Hôi Hột Tính Toán chứ không phải Thuê Giá Cao Xong Bắt Lằm Dài Trên Giường Nhàn Rỗi Đi Chơi). Do vậy Đồ thị chọc đỉnh CPU Utilization nhấp nhô liên hoàng xung quanh mức 75% đến 85% mới chứng tỏ bạn Config Size Máy Chạy Job quá Chuẩn, Chẳng thèm Nhét Quá Tải Để Chết Sụp, nhưng cũng không mua ngần Mua Mấy Node Dư Xăng thừa Thái Bỏ Không.",
    87: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính kiến thức: Spark Driver log4J ghi chép Text log nôm na. Tìm Chuỗi bóc Data thì Thần khí muôn thuở là A). Để vọc vạch thấu lõi nội dung Log thô chữ nghĩa hầm bà lằng (Stack trace, Error lines), công cụ Regular Expressions (Regex - Biểu thức chính quy) luôn là chiếc rổ lọc ma thuật tốt nhất mà Data Engineers hay nhét vào Python / Bash hòng múc ra từng Keyword báu vật mà mình đang lần mò sửa lỗi.",
    88: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nViệc code assert kiểm định ĐỘ CHÍNH XÁC CHẶT CHẼ của một Hàm nhỏ xinh (MyIntegrate) không đâm chọt qua DB, không nối mạng tới App thứ 3 nào, thì nó Chính là Minh Chứng cho Unit Test. Unit (Đơn Vị) là chặt vỡ Code Base của Pipeline Lớn Ra Test Tính Đúng Đắn Thuật Toán Từng Cục Nhỏ Một để Khỏi Sập Từ Chân Tơ Kẽ Tóc.",
    89: "✅ Đáp án đúng: E\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính chuẩn Databricks Workflow: Job Graph DAG không Cứu Thế Rollback theo Global). Do B và C là Chư Hầu rập đầu chờ Task A báo Khởi Nghĩa Thành Công thì mới Vác Giáo Tiến Đánh. Nhưng ôi thôi Task A chạy được nửa Mã thì Thắt Cổ Tự Vẫn (Stage Failure). Lúc Đó Đội Quân A ngã gục, B và C thấy A chập Mạch Lẽ Dĩ Nhiên Sẽ Nằm Yên Dưỡng Thương (Skipped Trắng), Mặc nhiên Mớ Data dở dang A chưa kịp Commit Thành Bản Lệnh Parquet Chốt Cuối. Tất cả im lìm như chưa từng xảy ra.",
    90: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nNếu User truy cập mục Advanced Options => Spark Config ngay Giao Diện Cài Đặt Cluster UI để chèn Thông Số Kỹ Thuật (VD. `spark.sql.shuffle.partitions 200`). Cái lồng kính Cluster Này Sẽ Hấp Thụ Dưỡng Chất Đó Và Truyền Xuống Thấm Vào Toàn Bộ Mạng Lưới Nhánh Notebook Nào đang bấm Nuốt Chửng Attach Vào Nó, Biến Thành Cấu Hình Hệ Tôn Quyết Định Toàn Lực Lượng Tính Toán Phía Dưới.",
    91: "✅ Đáp án đúng: E\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nMuốn Hợp Tác Góp Công Sửa Dòng Thay Đổi Lên Nhánh Main Tôn Nghiêm MÀ KHÔNG DÁM ĐỤNG CHẠM PHÁ VỠ SỨC KHỎE CỦA ANH EM KHÁC. Developer phải thực hành Nghi Thức Git Chấn Phái: 1. Đẻ 1 Branch mới Tinh Mát Mẻ (Tạo Nhánh), 2. Push Code Vừa Mài Giũa Lên cái Nhánh Riêng Ấy, 3. Viết Thư Xưng Tội Tâng Lên Cho Đại Sứ Tổ Trưởng Duyệt Gộp Trọng Kiểm Lỗi Vào Nhánh Chính Bằng Kỹ Thuật Kéo Chăn (Pull Request).",
    92: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nShallow Clone (Bản sao Cạn) là dạng Copy Cực Kỳ Mỏng Manh. Thay Vì Hủy Hoại Môi Trường In Ra Bản Sao Tốn Data Bạc Tỉ (Deep Clone), Nó Chỉ Copy Ra 1 Cuốn Sổ Metastore Mới ĐÍNH KÈM CON TRỎ TRỎ CƯỚP ĐỊA CHỈ FILE DỮ LIỆU CŨ. Nếu Cái Thằng Main Nó Đem Lệnh Diệt Vong VACUUM Đẩy Xác File Rác Ở Nơi Chứa Xóa Sạch, Cái Cuốn Sổ Kéo Con Trỏ Của Thằng Hậu Duệ Shallow Nhìn Ra Vùng Đất Chết Và Quét Lỗi Thủng File Bể Banh Ngay Lập Tức.",
    93: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\n(Đính chính theo Spark Structured Streaming Docs). Streaming engine không duy trì cục máu Tĩnh (Static Data) của luồng Không có ranh giới Cuối. Do Vậy Nếu Bọn Static Thúc Ép (Right/Left) Mà Đòi Giữ Tất Cả Tạp Pí lù Từ Bản STREAM Dạng NULL Dễ Thương NẰM CHƯỚT OUTER Biên, Engine Stream Sẽ Biểu Tình Nghỉ Làm Sập Job Ngay Lập Tức Vì Nổ Tung State Ram (Thiếu Memory Đợi Bản Ghi Không Hề Tồn Tại). Nên Nhớ Cấm Dùng Full Outer Liên Doanh giữa Luồng Nước Lũ Luân Hồi Mà Nhập Cùng Đá Cứng.",
    94: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nHiện Tượng Spill Bục Đáy (Nghẽn Dạ Dày Ram Spark Trôi Tuột Xuống Đĩa Cứng Lề Mề) Hiện Dạng Rõ Mồn Một Như Ma Xét Rõ Trong Bóng Đêm: Một là Ở Spark Stage Details Bảng Table Xem Memory/Disk Spill Cột Byte Mập Ú Lên Xanh Đỏ, Và Hai LÀ Chui Nằm Trực Rút Console Executor Log Chực Chóng Mặt Dò Dẫm Cái Dữ Kiện Báo Hiệu Hồi Trống Tràn Bộ Nhớ Nóng Hội.",
    95: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nVới Bảng Batch Đơn Côi Nghèo Nàn Chạy Data Khô Khan Qua Notebook Hằng Giờ Để DropDuplicate(order_id) Rồi APPEND Úp Mã Rác Vào. Nó Chỉ Thanh Tẩy Trùng Lặp CÙNG LỔ TRONG 1 MICROBATCH/INTERVAL Đó thôi. Chứ Nếu Order A Nằm Tại Giờ Thứ 1, Sau Hai Chuyến Đò Nữa Ỏ Giờ Thứ 3 Order A Hiện Hồn Phản Phất Khất Nợ Chạy Lại, Cái Lệnh Gắp Bỏ Append Tinh Sương Ngây Ngô Này Nào Đâu Nhớ Mặt Nó Từng Ghi Danh Vào Delta Table Cách Đây Nửa Thế Kỷ, Thế Là Hai Thằng A Ngay Lập Tức Du Hành Cùng Tồn Tại Cười Toe Toét (Duplicate records preserved > 2 hours).",
    96: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nSự Đau Đớn Của Các Con Chiên RDBMS Cổ Đại (MySQL, Postgres) Sang Làm Phù Thủy Data Lakehouse LÀ Spark KHÔNG CÓ THÓI QUEN Áp Phân Khắc Ràng Buộc Khóa Ngoại (Foreign Key Enforcements). Kéo Lệnh INSERT CHÙM qua 5 Bảng Hòng Chặn Mồ Lệch FK - PK Xin Chúc Mừng Bề Lỗi Nát Tim. Lakehouse Đơn Phương ACID Cứng Từng Bảng Một. Kỹ Sư Phải Dịch Chuyển Tâm Trí Rành Rọt Tự Xác Min Validation Quality Rule Vứt Lên Tầng Trước Bằng Expectations Or Assert Nhé.",
    97: "✅ Đáp án đúng: D\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nTại Sao Giới Kỹ Sư Data Không Xài Trò Ghi Đè (Type 1) Rồi Ăn Mày Dĩ Vãng Rút Mảnh Khứ Delta Log (Time Travel) Thành Slowly Changing Dimension Toàn Năng? LÀ BỞI VÌ Nếu Hãng Để Mặc Delta Transaction Logs Phình Dày Bằng Quỹ Đạo Bánh Tráng Khoảng Mấy Chục Triệu Json, Query Time Travel Cho Những Con Bảng Sống Cả Đời Người (Long-term) Vừa Nặng Chịch Băng Thông Vừa Phóng Error Khóc Bùm Vì Thằng Admin Có Khi Đã Lỡ Tay Vẩy Cây Chổi Phép Vacuum Cướp Bến Mất Xấu Chết History Bảy Đời Của Làng Nghĩa Địa Xưa Mất Rất D.",
    98: "✅ Đáp án đúng: A\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nMột Bài Kiểm Tra Kinh Quãng Sâu Về Dynamic View Trong Lakehouse Cục Bộ: Logic Câu Lệnh Phán Xử \"TẾ BÀO MẤT TÍCH\" Sẽ Hiện Biến Rõ Ràng Như Lưới Thần. Nếu Thằng Analyst Mở Kính Chọn Đọc Và Đeo Mác Group Lạ Hoắc (Chẳng Thuộc Ban Auditing Kiểm Duyệt Nội Bộ), Cửa Xoay Lệnh CASE/FILTER Của View Tương Áp Buộc Đóng Chặt Cửa Kho Và Đá Bật Toàn Bộ Khối Trẻ Trâu Bồi Mệnh Nào Dám Mang Tuổi Nhỏ Hơn Lỗ 18 (Omitted Dứt Khoát). Không Có Data Rỗng Báo Về Đâu, Null Cái Gì Gọi Là Bay Tuột Hành Tinh Nhón.",
    99: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nDelta Lake Cho Bạn Thanh Toàn Lửa Cháy Hồn Giác Quan Ở Log Table, Rằng Gã Khách Này (User_id Nhỏ Bé Kia) Không Bao Giờ Cho Hiện Hình Trong Việc SELECT Mới Mẻ Nào Nữa Hết Nghe Chưa. ACID Gật Đầu Xác Nhận! Nhưng Nếu Interpol Luật Pháp Hoặc Compliance Auditor GDPR Vác Súng Gõ Cửa Lùng Bắt Kháng Cáo Ở Level Disk Vân Khói Lưới Storage Chỗ Tận Cùng Đất S3 Mây: Thì TẬP TIN PARQUET HOÀN TOÀN CÒN Y NGUYÊN (Cho Tặng Đám Time Travel Ăn Ngân Chơi Ngông Hết Hạn Trữ Ngày). Vacuum Mới Chính Là Bùa Phép Hỗ Trợ Đốt Trụi Xác Pháp Chân Thực Nghĩa Nhất.",
    100: "✅ Đáp án đúng: B\n\n💡 Giải thích chi tiết từ Trợ lý AI:\nXây Dựng Ống Khóa Kho Tàng Mật Mã Giữa Non-Databricks Connector Sang Mồi Phím Spark Ảo Phối Giới Bí Thuật Hữu Ý, Nước Phẳng Cờ Yên Là Ta Nhốt Cái Chìa Khóa Login Mật Của Database Chứa Đựng Chì Lịch Group \"Mới Nhất Màn Trong Mũ\" Vào Bên Tron Secret Scope Của Databricks. Bọn Đàn Em Developer Nặng Phím Data Chỉ Được Cấp Cho Đúng 1 Sợi Giây Thòng Lọng Quyền `\"READ\"` Bí Mật Ở Cái Lộ Chìa Khóa Đo Từng Nhà Trú Dân Nhóm Họ Mà Đọc Cho Thông Suốt Khỏi Phải Nhìn Chằm Chằm Chữ Bí Ẩn Vào DB Thế Gian Đó Là Thôi."
}

def main():
    data = load_data()
    updated = 0
    for q in data:
        qid = q["id"]
        # Standardize true answers found in PDFs by AI review
        if qid == 71: q["answer"] = "A" # PDF has D, correct is A
        if qid == 74: q["answer"] = "D" # PDF has C, correct is D
        if qid == 75: q["answer"] = "C" # PDF has D, correct is C
        if qid == 81: q["answer"] = "B" # PDF has D, correct is B
        if qid == 83: q["answer"] = "E" # PDF has D, correct is E
        if qid == 84: q["answer"] = "D" # PDF has E, correct is D
        if qid == 85: q["answer"] = "D" # PDF has C, correct is D
        if qid == 86: q["answer"] = "E" # PDF has D, correct is E
        if qid == 87: q["answer"] = "A" # PDF has E, correct is A
        if qid == 89: q["answer"] = "E" # PDF has C, correct is E
        if qid == 93: q["answer"] = "B" # PDF has E, correct is B

        if qid in manual_explanations:
            q["explanation_vi"] = manual_explanations[qid]
            updated += 1
            
    save_data(data)
    print(f"Injected custom explanations for Q71 - Q100! ({updated} questions updated)")

if __name__ == "__main__":
    main()
