const fs = require('fs');
const path = require('path');

const data = {
  "concepts/1-distributed-systems-architecture/consensus-raft-paxos.md": "Các thuật toán đồng thuận (Consensus Algorithms) như Raft hay Paxos là cốt lõi của các hệ thống phân tán. Chúng giải quyết bài toán làm thế nào để một cụm máy chủ có thể thống nhất chung một trạng thái dữ liệu ngay cả khi một vài máy trong cụm bị tắt đột ngột (Node Failure) hoặc mất mạng tạm thời.",
  "concepts/1-distributed-systems-architecture/context-window.md": "Context Window (Cửa sổ ngữ cảnh) là giới hạn bộ nhớ ngắn hạn của một LLM trong một lần phản hồi. Ví dụ, một mô hình có Context Window là 8,000 tokens nghĩa là nó chỉ có thể 'đọc' và 'nhớ' tối đa khoảng 6,000 từ cùng lúc. Mọi thông tin nằm ngoài cửa sổ này sẽ bị lãng quên.",
  "concepts/1-distributed-systems-architecture/data-engineer-role.md": "Data Engineer (Kỹ sư Dữ liệu) là người chịu trách nhiệm xây dựng hạ tầng, luồng chảy và kiến trúc để thu thập, làm sạch và lưu trữ dữ liệu quy mô lớn. Khác với Data Scientist tập trung vào việc dự đoán, Data Engineer tập trung vào khía cạnh 'Software Engineering' để đảm bảo dữ liệu luôn sẵn sàng, chính xác và có thể truy cập nhanh chóng.",
  "concepts/1-distributed-systems-architecture/data-engineering.md": "Data Engineering là ngành khoa học về việc thiết kế và xây dựng các hệ thống để xử lý khối lượng dữ liệu khổng lồ (Big Data). Nó bao trùm toàn bộ vòng đời từ việc lập trình kéo dữ liệu (Ingestion), chuyển đổi logic kinh doanh (Transformation), cho đến tối ưu hóa chi phí lưu trữ (Storage Optimization).",
  "concepts/1-distributed-systems-architecture/data-fabric.md": "Data Fabric là một kiến trúc quản trị dữ liệu dựa trên AI, tập trung vào việc tự động hóa việc kết nối các nguồn dữ liệu rời rạc thông qua Metadata (Siêu dữ liệu). Khác với Data Mesh tập trung vào yếu tố con người và Domain, Data Fabric dựa dẫm hoàn toàn vào máy móc và Machine Learning để tích hợp dữ liệu.",
  "concepts/1-distributed-systems-architecture/data-lifecycle.md": "Data Lifecycle (Vòng đời dữ liệu) bao gồm các giai đoạn: Tạo ra (Generation), Thu thập (Collection), Lưu trữ (Storage), Xử lý (Processing), Phân tích (Analysis), và cuối cùng là Lưu trữ lạnh hoặc Xóa (Archiving/Purging). Data Engineer chịu trách nhiệm đảm bảo dữ liệu di chuyển trơn tru qua từng giai đoạn này.",
  "concepts/1-distributed-systems-architecture/data-mesh.md": "Data Mesh là một mô hình tổ chức dữ liệu phi tập trung (Decentralized). Thay vì một team Data Engineer trung tâm phải lo liệu mọi thứ gây thắt cổ chai, Data Mesh giao quyền sở hữu dữ liệu (Data as a Product) cho từng phòng ban (Domains), giúp họ tự do xây dựng và chia sẻ dữ liệu của riêng mình.",
  "concepts/1-distributed-systems-architecture/data-platform-architecture.md": "Data Platform Architecture là bộ khung thiết kế toàn diện bao gồm các công cụ Ingestion (Kafka/Fivetran), Storage (S3/Snowflake), Processing (Spark/dbt), và Orchestration (Airflow). Mục tiêu của một kiến trúc tốt là phải đảm bảo tính mở rộng (Scalability), tính linh hoạt (Agility) và khả năng bảo trì cao.",
  "concepts/1-distributed-systems-architecture/data-warehouse.md": "Data Warehouse (Kho dữ liệu) là hệ thống cơ sở dữ liệu chuyên dụng để lưu trữ dữ liệu đã được làm sạch và cấu trúc chặt chẽ (Structured Data) từ nhiều nguồn khác nhau. Nó được tối ưu hóa đặc biệt (Columnar Storage) để thực hiện các câu truy vấn phân tích (OLAP) và phục vụ cho BI/Báo cáo.",
  "concepts/1-distributed-systems-architecture/evaluation-metric.md": "Evaluation Metric (Chỉ số đánh giá) là các công thức toán học dùng để đo lường độ chính xác của các mô hình Machine Learning hoặc hệ thống RAG. Trong bài toán tìm kiếm, các chỉ số phổ biến bao gồm Precision, Recall, và NDCG để đo mức độ liên quan của kết quả trả về.",
  "concepts/1-distributed-systems-architecture/event-driven-architecture.md": "Kiến trúc hướng sự kiện (Event-Driven Architecture) là thiết kế phần mềm trong đó các microservices giao tiếp với nhau bằng cách phát ra và lắng nghe các sự kiện (Events) thông qua một Message Broker (như Kafka) thay vì gọi API trực tiếp. Điều này giúp hệ thống tách rời (Decoupled) và chịu tải cực tốt.",
  "concepts/1-distributed-systems-architecture/feature-store.md": "Feature Store là một kho chứa chuyên dụng dành riêng cho Machine Learning. Nó tính toán, lưu trữ và quản lý các 'đặc trưng' (Features - ví dụ: Số lần mua hàng trong 30 ngày qua) để các Data Scientist có thể dễ dàng tái sử dụng chung một logic cho việc huấn luyện (Offline) và dự đoán trực tiếp (Online).",
  "concepts/1-distributed-systems-architecture/few-shot.md": "Few-Shot Prompting là kỹ thuật đưa một vài ví dụ (thường từ 2 đến 5 ví dụ) về Input và Output vào thẳng trong câu lệnh (Prompt) của mô hình LLM. Điều này giúp định hướng mô hình trả về kết quả theo đúng định dạng và văn phong mong muốn mà không cần phải train lại (Fine-tuning) mô hình.",
  "concepts/1-distributed-systems-architecture/file-formats.md": "Định dạng file (File Formats) quyết định cách dữ liệu được mã hóa trên đĩa. Trong Data Engineering, các định dạng Columnar (như Parquet, ORC) thống trị trong phân tích vì khả năng nén siêu việt, trong khi các định dạng Row-based (như Avro, JSON) lại thống trị trong các luồng dữ liệu Streaming (Kafka) vì sự linh hoạt.",
  "concepts/1-distributed-systems-architecture/fine-tuning.md": "Fine-tuning là quá trình tinh chỉnh lại trọng số của một mô hình AI đã được huấn luyện sẵn (Pre-trained) bằng một tập dữ liệu nhỏ mang tính chuyên ngành. Việc này giúp mô hình nắm bắt được văn phong hoặc tri thức đặc thù của doanh nghiệp mà RAG không thể thay thế được.",
  "concepts/1-distributed-systems-architecture/gossip-protocol.md": "Gossip Protocol là một giao thức mạng lấy cảm hứng từ 'tin đồn'. Trong các hệ thống như Cassandra, thay vì có một máy chủ trung tâm giám sát, mỗi Node sẽ liên tục rỉ tai (gossip) tình trạng của mình cho vài Node ngẫu nhiên lân cận. Chỉ sau vài giây, cả mạng lưới hàng ngàn máy sẽ biết máy nào đang bị chết.",
  "concepts/1-distributed-systems-architecture/hallucination.md": "Hallucination (Ảo giác) là hiện tượng mô hình AI (như ChatGPT) tự bịa ra thông tin sai lệch nhưng trình bày với một thái độ cực kỳ tự tin và thuyết phục. Đây là rủi ro lớn nhất trong việc áp dụng GenAI, đòi hỏi phải sử dụng RAG hoặc Grounding để ép mô hình chỉ được nói sự thật.",
  "concepts/1-distributed-systems-architecture/kappa-architecture.md": "Kappa Architecture là kiến trúc dữ liệu đơn giản hóa Lambda. Nó loại bỏ hoàn toàn hệ thống xử lý Batch chậm chạp. Thay vào đó, tất cả dữ liệu (dù là lịch sử hay thời gian thực) đều được đẩy qua một hệ thống Streaming duy nhất (như Kafka + Flink).",
  "concepts/1-distributed-systems-architecture/lambda-architecture.md": "Lambda Architecture là kiến trúc cổ điển chia luồng dữ liệu làm 2 nhánh chạy song song: Nhánh Batch (chậm nhưng chính xác tuyệt đối, chạy Hadoop/Spark) và Nhánh Speed (nhanh nhưng có thể sai số, chạy Storm/Flink). Cuối cùng, tầng Serving sẽ gộp kết quả của 2 nhánh lại cho người dùng.",
  "concepts/1-distributed-systems-architecture/leader-election.md": "Leader Election (Bầu cử thủ lĩnh) là cơ chế bắt buộc khi bạn có nhiều máy chủ chạy song song nhưng chỉ được phép có 1 máy đưa ra quyết định (để tránh xung đột). Zookeeper, etcd, và thuật toán Raft là những công nghệ tiêu chuẩn để tổ chức các cuộc 'bầu cử' này một cách tự động và công bằng.",
  "concepts/1-distributed-systems-architecture/lora.md": "LoRA (Low-Rank Adaptation) là một kỹ thuật Fine-tuning siêu tiết kiệm tài nguyên. Thay vì cập nhật hàng chục tỷ tham số của LLM (cực tốn VRAM), LoRA chỉ 'đóng băng' mô hình gốc và chèn thêm một vài ma trận nhỏ (low-rank matrices) vào mạng neural, giúp huấn luyện mô hình mạnh trên một GPU dân dụng.",
  "concepts/1-distributed-systems-architecture/mlflow.md": "MLflow là nền tảng mã nguồn mở (được tạo bởi Databricks) dùng để quản lý toàn bộ vòng đời của Machine Learning (MLOps). Nó theo dõi các thông số chạy thử nghiệm (Tracking), lưu trữ mô hình (Model Registry), và đóng gói code để dễ dàng triển khai từ Laptop lên Production.",
  "concepts/1-distributed-systems-architecture/model-serving.md": "Model Serving là quá trình đóng gói một mô hình Machine Learning đã được huấn luyện xong thành một dịch vụ (thường là REST API hoặc gRPC) để các phần mềm khác có thể gọi vào và lấy dự đoán (Inference). Tốc độ (Low Latency) và khả năng chịu tải cao là yêu cầu cốt lõi của Model Serving.",
  "concepts/1-distributed-systems-architecture/modern-data-stack.md": "Modern Data Stack (MDS) là một bộ công cụ dữ liệu thế hệ mới dựa hoàn toàn trên Cloud, nhấn mạnh vào sự dễ dùng và mô hình ELT. Khối xây dựng tiêu chuẩn thường bao gồm: Fivetran (Ingestion), Snowflake/BigQuery (Data Warehouse), dbt (Transformation), và Looker (BI).",
  "concepts/1-distributed-systems-architecture/ndcg.md": "NDCG (Normalized Discounted Cumulative Gain) là một chỉ số cực kỳ quan trọng dùng để đánh giá các thuật toán Xếp hạng (Ranking) và hệ thống RAG. Nó không chỉ quan tâm đến việc 'Có trả về tài liệu đúng không' mà còn chú trọng việc 'Tài liệu đúng nhất có nằm ở top 1 hay không'.",
  "concepts/1-distributed-systems-architecture/pacelc-theorem.md": "Định lý PACELC là sự mở rộng của định lý CAP. Nó khẳng định rằng: Nếu hệ thống bị chia cắt mạng (P), bạn phải chọn giữa Tính Khả dụng (A) hoặc Tính Nhất quán (C). Nhưng ngay cả khi hệ thống BÌNH THƯỜNG (E - Else), bạn vẫn phải đánh đổi giữa Độ Trễ thấp (L - Latency) hoặc Tính Nhất quán (C).",
  "concepts/1-distributed-systems-architecture/peft.md": "PEFT (Parameter-Efficient Fine-Tuning) là thuật ngữ chung chỉ các phương pháp (như LoRA, Prefix Tuning) cho phép Fine-tune các Mô hình Ngôn ngữ Lớn (LLM) bằng cách chỉ cập nhật một số lượng tham số rất nhỏ, giảm thiểu hàng chục lần chi phí tính toán và bộ nhớ so với Full Fine-tuning.",
  "concepts/1-distributed-systems-architecture/push-pull-delivery.md": "Trong truyền tải dữ liệu, Push là mô hình mà bên sản xuất chủ động đẩy dữ liệu sang bên tiêu thụ (thích hợp cho real-time alert). Ngược lại, Pull là mô hình mà bên tiêu thụ chủ động kéo dữ liệu về theo tốc độ của riêng mình (như Kafka Consumer), giúp tránh bị quá tải (backpressure).",
  "concepts/1-distributed-systems-architecture/real-time-architecture.md": "Real-time Architecture (Kiến trúc thời gian thực) là các thiết kế hệ thống đảm bảo độ trễ từ khi sự kiện xảy ra đến khi có trong báo cáo chỉ tính bằng giây hoặc mili-giây. Nó thường dựa vào các công cụ Event Streaming (Kafka), Stream Processing (Flink), và Real-time OLAP (Pinot/Druid).",
  "concepts/1-distributed-systems-architecture/recall.md": "Recall (Độ phủ) là một chỉ số đánh giá độ hiệu quả của thuật toán tìm kiếm. Nó trả lời câu hỏi: 'Trong số TẤT CẢ các tài liệu thực sự liên quan đang có trong kho, hệ thống đã tìm ra được bao nhiêu phần trăm?'. Cùng với Precision (Độ chính xác), Recall là thước đo cốt lõi của RAG."
};

const docsDir = path.join(__dirname, '../src/content/docs');
let count = 0;
for (const [relPath, content] of Object.entries(data)) {
  const fullPath = path.join(docsDir, relPath);
  if (fs.existsSync(fullPath)) {
    const original = fs.readFileSync(fullPath, 'utf-8');
    const match = original.match(/^(---\n[\s\S]*?\n---\n)/);
    if (match) {
      const frontmatter = match[1];
      const references = original.includes('## Tài Liệu Tham Khảo') 
                         ? original.substring(original.indexOf('## Tài Liệu Tham Khảo'))
                         : '## Tài Liệu Tham Khảo\n* [Designing Data-Intensive Applications - Martin Kleppmann](https://dataintensive.net/)\n* [System Design Interview - Alex Xu](https://bytebytego.com/)';
      const newFileContent = `${frontmatter}\n${content}\n\n${references}`;
      fs.writeFileSync(fullPath, newFileContent, 'utf-8');
      count++;
    }
  }
}
console.log(`Updated ${count} files in batch 6.`);
