const fs = require('fs');
const path = require('path');

const data = {
  "concepts/1-distributed-systems-architecture/relational-database.md": "Relational Database (Cơ sở dữ liệu quan hệ) như MySQL hay PostgreSQL lưu trữ dữ liệu dưới dạng các bảng có cấu trúc nghiêm ngặt (hàng và cột), tuân thủ nguyên lý ACID. Nó được thiết kế bằng cấu trúc B-Tree để tối ưu hóa cho các giao dịch kinh doanh (OLTP) tốc độ cao, nhưng lại yếu thế trước các truy vấn phân tích quy mô lớn.",
  "concepts/1-distributed-systems-architecture/reranker.md": "Reranker (Mô hình xếp hạng lại) là một Cross-Encoder Neural Network được đặt ở cuối luồng xử lý RAG. Nó nhận vào danh sách các tài liệu đã được tìm thấy bởi Semantic Search, rồi đánh giá chi tiết (cho điểm) sự tương quan giữa câu hỏi của người dùng và từng tài liệu, sau đó sắp xếp lại kết quả để đẩy cái chính xác nhất lên top 1.",
  "concepts/1-distributed-systems-architecture/reranking.md": "Reranking là bước sàng lọc thứ hai vô cùng quan trọng trong tìm kiếm. Thay vì tin tưởng mù quáng vào thuật toán tìm kiếm Vector (thường ưu tiên tốc độ hơn độ chính xác tuyệt đối), hệ thống Reranking sẽ cẩn thận chấm điểm lại top 50 kết quả bằng một mô hình Machine Learning đắt đỏ hơn để tăng tối đa độ chính xác (Precision).",
  "concepts/1-distributed-systems-architecture/rlhf.md": "RLHF (Reinforcement Learning from Human Feedback) là bí quyết đằng sau sự thành công của ChatGPT. Đây là quá trình huấn luyện bổ sung, nơi con người đánh giá và chấm điểm các câu trả lời của mô hình. Dựa trên phản hồi này, mô hình học được cách cư xử lịch sự, từ chối câu hỏi độc hại và phù hợp với 'giá trị con người' (Alignment).",
  "concepts/1-distributed-systems-architecture/source-systems.md": "Source Systems (Hệ thống nguồn) là nơi khai sinh ra dữ liệu gốc của doanh nghiệp, chẳng hạn như CRM (Salesforce), ERP (SAP), Database của App (PostgreSQL), hoặc Web Analytics (Google Analytics). Trách nhiệm của Data Engineer là hút dữ liệu từ Source Systems một cách an toàn mà không làm hệ thống này sụp đổ.",
  "concepts/1-distributed-systems-architecture/storage-compute-decoupling.md": "Phân tách Lưu trữ và Tính toán (Decoupling Storage and Compute) là nguyên lý thiết kế tối thượng của Cloud Data Warehouse (như Snowflake). Nó cho phép bạn lưu trữ hàng Petabyte dữ liệu trên S3 cực rẻ (Storage), và chỉ thuê máy chủ CPU khổng lồ (Compute) trong đúng 10 giây khi cần chạy truy vấn, tiết kiệm chi phí tối đa.",
  "concepts/1-distributed-systems-architecture/temperature.md": "Temperature (Nhiệt độ) là một tham số điều chỉnh sự 'sáng tạo' của LLM. Ở mức 0.0, LLM trở nên khô khan, chính xác và luôn chọn từ ngữ có xác suất cao nhất (rất tốt cho RAG/Coding). Ở mức 1.0 trở lên, mô hình dám chọn những từ ngữ đột phá, tăng tính bay bổng sáng tạo nhưng rủi ro Halucination cao hơn.",
  "concepts/1-distributed-systems-architecture/token.md": "Token là đơn vị xử lý cơ bản nhất của LLM. Một Token không nhất thiết phải là một từ nguyên vẹn; nó có thể là một âm tiết, một chữ cái, hoặc một phần của từ. Ví dụ: từ 'Hamburger' có thể bị chia thành 3 tokens ('Ham', 'bur', 'ger'). LLM tính tiền dựa trên số lượng Tokens đầu vào và đầu ra.",
  "concepts/1-distributed-systems-architecture/top-p.md": "Top-p (hay Nucleus Sampling) là một phương pháp giới hạn sự lựa chọn từ vựng của LLM. Thay vì chọn từ hoàn toàn ngẫu nhiên, mô hình chỉ được phép chọn trong tập hợp các từ mà tổng xác suất cộng lại đạt một ngưỡng 'p' (VD: 0.9). Điều này cắt bỏ những từ quá kỳ quặc ở đuôi phân phối, giữ cho câu văn mạch lạc.",
  "concepts/1-distributed-systems-architecture/zero-copy-cloning.md": "Zero-Copy Cloning là tính năng 'sao chép ma thuật' của Snowflake và Delta Lake. Nó cho phép bạn nhân bản (Clone) một bảng dữ liệu 1 Terabyte ngay lập tức mà không tốn một Byte ổ cứng nào thêm. Nó thực chất chỉ nhân bản Metadata (con trỏ), rất tuyệt vời cho việc tạo môi trường Test/Dev tức thì.",
  "concepts/1-distributed-systems-architecture/zero-shot.md": "Zero-Shot Prompting là tình huống người dùng đưa yêu cầu thẳng thừng cho LLM mà không mớm trước bất kỳ ví dụ nào (No Examples). Mô hình phải dựa hoàn toàn vào 'kiến thức bản năng' đã học trong quá trình pre-training để hiểu ý định và định dạng cần thiết để phản hồi.",

  "concepts/2-data-ingestion-integration/backfill.md": "Backfill (Điền lấp lịch sử) là quá trình chạy lại Data Pipeline cho các mốc thời gian trong quá khứ. Bạn thường phải Backfill khi thêm một cột mới vào bảng, khi phát hiện logic tính toán cũ bị sai, hoặc khi khởi tạo một bảng dữ liệu mới và cần dữ liệu của 3 năm trước đó.",
  "concepts/2-data-ingestion-integration/backpressure-handling.md": "Backpressure (Áp lực ngược) xảy ra trong Streaming khi hệ thống sinh ra dữ liệu (Producer) chạy quá nhanh, làm hệ thống xử lý (Consumer) bị ngộp thở. Các framework như Flink hoặc Kafka xử lý bằng cách yêu cầu Producer giảm tốc độ lại, hoặc dùng bộ đệm khổng lồ trên ổ cứng để hứng chịu lượng dư thừa.",
  "concepts/2-data-ingestion-integration/change-data-capture.md": "CDC (Change Data Capture) là cơ chế bắt giữ mọi thay đổi (INSERT, UPDATE, DELETE) xảy ra trong Database nguồn theo thời gian thực (thường là đọc từ Transaction Log/Binlog) rồi đẩy lên Kafka. Nó cho phép đồng bộ hóa dữ liệu xuống Data Warehouse với độ trễ cực thấp mà không làm nặng Database gốc.",
  "concepts/2-data-ingestion-integration/data-extraction.md": "Data Extraction (Khai xuất dữ liệu) là bước E trong quá trình ETL. Đây là nghệ thuật kết nối và kéo dữ liệu ra khỏi các hệ thống nguồn hỗn tạp (API, SQL DB, MongoDB, FTP) một cách an toàn nhất, sử dụng Incremental Extraction (chỉ lấy phần mới) để giảm thiểu I/O và áp lực lên hệ thống.",
  "concepts/2-data-ingestion-integration/data-ingestion.md": "Data Ingestion (Thu nạp dữ liệu) là cửa ngõ đầu tiên của mọi Data Pipeline. Nhiệm vụ của nó là di chuyển dữ liệu từ hệ thống bên ngoài vào trong Data Lake/Warehouse của bạn. Ingestion có thể chạy theo lô (Batch) mỗi đêm hoặc chạy liên tục theo luồng thời gian thực (Streaming).",
  "concepts/2-data-ingestion-integration/data-loading.md": "Data Loading (Tải dữ liệu) là bước L trong ETL/ELT. Khác với các hệ thống OLTP chèn từng dòng lệnh INSERT chậm chạp, Data Loading thường sử dụng các công cụ tải hàng loạt (Bulk Load) như lệnh COPY INTO của Snowflake hay BigQuery để nạp hàng triệu dòng dữ liệu vào kho trong chớp mắt.",
  "concepts/2-data-ingestion-integration/data-transformation.md": "Data Transformation (Biến đổi dữ liệu) là trái tim của Data Engineering, nơi dữ liệu thô (Raw) được nhào nặn thành giá trị nghiệp vụ (Business Logic). Quá trình này bao gồm: Làm sạch (Cleaning), Chuẩn hóa (Standardization), Nối bảng (Joining), và Tổng hợp con số (Aggregation).",
  "concepts/2-data-ingestion-integration/deduplication.md": "Deduplication (Khử trùng lặp) là kỹ thuật loại bỏ các bản ghi bị nhân đôi trong hệ thống phân tán (ví dụ khi Kafka gửi lại một message do rớt mạng). Nó thường được giải quyết bằng các hàm cửa sổ (ROW_NUMBER) trong SQL, hoặc bằng cơ chế Exactly-Once Semantics của Spark/Flink.",
  "concepts/2-data-ingestion-integration/elt.md": "ELT (Extract, Load, Transform) là mô hình hiện đại thay thế ETL. Thay vì sử dụng một server trung gian xử lý biến đổi, dữ liệu được tải (Load) thẳng vào Cloud Data Warehouse dưới dạng thô. Sau đó, kỹ sư dùng sức mạnh điện toán vô hạn của chính Warehouse đó (qua dbt) để thực hiện biến đổi (Transform).",
  "concepts/2-data-ingestion-integration/etl.md": "ETL (Extract, Transform, Load) là mô hình truyền thống có từ thập kỷ 90. Dữ liệu được kéo ra khỏi nguồn, biến đổi trên một server ETL chuyên biệt (như Informatica, Talend), và sau khi đã sạch sẽ gọn gàng mới được đẩy vào Data Warehouse. Nhược điểm của nó là kém linh hoạt và thường bị thắt cổ chai tại server ETL.",
  "concepts/2-data-ingestion-integration/idempotency.md": "Idempotency (Tính Lũy đẳng) là đặc tính vàng của một Data Pipeline. Một Pipeline đạt chuẩn Idempotent thì dù bạn có bấm nút Chạy lại (Retry) 1 lần hay 100 lần cho cùng một ngày, kết quả cuối cùng trong Database vẫn giống hệt nhau, không bao giờ bị nhân đôi dữ liệu (Double-counting).",
  "concepts/2-data-ingestion-integration/incremental-load.md": "Incremental Load (Tải tăng dần) là chiến lược tối ưu Ingestion. Thay vì copy toàn bộ bảng Khách hàng 1 Tỷ dòng mỗi đêm (Full Load), Incremental Load chỉ quét và kéo về những khách hàng mới đăng ký hoặc cập nhật hồ sơ trong 24 giờ qua dựa trên cột `updated_at` hoặc Watermark.",
  "concepts/2-data-ingestion-integration/log-based-cdc-internals.md": "Log-based CDC là cơ chế đọc thẳng vào tệp nhật ký ghi trước của Database (ví dụ: WAL của Postgres, Binlog của MySQL) bằng các công cụ như Debezium. Việc này giúp bắt trọn vẹn mọi thay đổi mà không phải chạy lệnh `SELECT *` tốn kém, hoàn toàn ẩn danh và không ảnh hưởng đến người dùng DB.",
  "concepts/2-data-ingestion-integration/webhook-idempotency.md": "Khi tích hợp Webhook từ các nền tảng (như Stripe báo thanh toán thành công), việc mạng bị lag có thể khiến Stripe gửi trùng 2 cái Webhook giống hệt nhau. Để đảm bảo Idempotency, Data Pipeline phải lưu trữ `Event_ID` vào Cache/Database để nếu nhận được Event_ID trùng lặp, nó sẽ bỏ qua không xử lý.",

  "concepts/3-storage-engines-formats/acid-transactions-on-lake.md": "Giao dịch ACID trên Data Lake từng là một giấc mơ xa vời cho đến khi Delta Lake và Iceberg xuất hiện. Chúng cho phép bạn thực hiện thao tác UPDATE/DELETE trên hàng ngàn file Parquet nằm rải rác trên S3 một cách an toàn. Nếu job bị sập giữa chừng, hệ thống tự động Rollback (quay xe) bảo vệ tính nguyên vẹn của dữ liệu.",
  "concepts/3-storage-engines-formats/amazon-redshift.md": "Amazon Redshift là Data Warehouse đám mây phổ biến nhất thế hệ đầu tiên trên AWS. Dựa trên lõi PostgreSQL được viết lại thành kiến trúc MPP Columnar, Redshift mạnh mẽ trong phân tích nhưng gặp hạn chế vì kiến trúc cũ của nó kết dính chặt chẽ Compute và Storage vào chung một Node vật lý.",
  "concepts/3-storage-engines-formats/apache-hudi.md": "Apache Hudi (Hadoop Upserts Deletes and Incrementals) là một Open Table Format được tạo ra bởi Uber. Thế mạnh lớn nhất của Hudi so với Iceberg/Delta là khả năng cực mạnh trong xử lý Streaming, Upsert liên tục và có các cơ chế Indexing tinh vi (Bloom Filter Index) để thay đổi dữ liệu thời gian thực.",
  "concepts/3-storage-engines-formats/apache-iceberg.md": "Apache Iceberg là một Open Table Format do Netflix tạo ra để sửa chữa những giới hạn của Apache Hive. Thay vì theo dõi Metadata bằng các Thư mục (Folders), Iceberg theo dõi danh sách từng File một cách rõ ràng. Điều này giúp Iceberg đọc cực nhanh, hỗ trợ ACID và Time Travel mà không sợ bị chậm do liệt kê file trên S3.",
  "concepts/3-storage-engines-formats/azure-synapse.md": "Azure Synapse Analytics là dịch vụ phân tích dữ liệu vô cực của Microsoft. Nó tham vọng hợp nhất (Unified) hoàn toàn giữa Data Warehouse truyền thống (SQL Dedicated Pools) và Data Lake/Big Data (Spark Pools), đi kèm với công cụ Orchestration (Synapse Pipelines) tích hợp sẵn trên một nền tảng.",
  "concepts/3-storage-engines-formats/b-tree-vs-lsm-tree.md": "B-Tree (cây cân bằng) là cấu trúc lõi của RDBMS truyền thống, tối ưu cho thao tác Đọc nhưng chậm khi Ghi liên tục. Ngược lại, LSM-Tree (Log-Structured Merge-Tree) là cấu trúc lõi của NoSQL và Time-Series DB (như Cassandra, RocksDB), sinh ra để tối ưu hóa việc Ghi (Write-Heavy) với tốc độ khủng khiếp bằng cách chỉ nối thêm (append-only).",
  "concepts/3-storage-engines-formats/cloud-storage.md": "Cloud Storage (Lưu trữ đối tượng trên Đám mây) như Amazon S3, Google GCS là cuộc cách mạng hạ tầng. Dữ liệu không được lưu theo dạng file hệ thống truyền thống (POSIX) mà lưu dưới dạng Object (có URI và Metadata). Nó có khả năng mở rộng vô hạn, độ bền (Durability) 99.999999999% và là trái tim của Data Lake hiện đại."
};

const docsDir = path.join(__dirname, '../src/content/docs');
let count = 0;
for (const [relPath, content] of Object.entries(data)) {
  const fullPath = path.join(docsDir, relPath);
  if (fs.existsSync(fullPath)) {
    const original = fs.readFileSync(fullPath, 'utf-8');
    const match = original.match(/^(---\n[\s\S]*?\n---\n)/);
    if (match) {
      const frontmatter = match[1];
      const references = original.includes('## Tài Liệu Tham Khảo') 
                         ? original.substring(original.indexOf('## Tài Liệu Tham Khảo'))
                         : '## Tài Liệu Tham Khảo\n* [Fundamentals of Data Engineering](https://www.oreilly.com/library/view/fundamentals-of-data/9781098108298/)\n* [Data Intensive Applications](https://dataintensive.net/)';
      const newFileContent = `${frontmatter}\n${content}\n\n${references}`;
      fs.writeFileSync(fullPath, newFileContent, 'utf-8');
      count++;
    }
  }
}
console.log(`Updated ${count} files in batch 7.`);
